### ISSUE TITLE
Support time.Time

### ISSUE THREAD

**Issue by rumpelsepp** [fxamacker/cbor#1]
Does it make sense for you to directly support time.Time struct fields in this lib? This guy supports it: https://github.com/ugorji/go/blob/02994ffebd8e7ef482130d13b570c8be0968b790/codec/cbor.go#L222

**Comment by fxamacker** [comment]
Thanks for the suggestion.  

I'm looking into it.

**Comment by fxamacker** [comment]
Just published a new release supporting time.Time encoding and decoding: https://github.com/fxamacker/cbor/releases/tag/v0.3.0

Please let me know if it works for you.

**Comment by rumpelsepp** [comment]
I migrated my codebase to the change already. Tests will be done this week. Thank you!

**Comment by fxamacker** [comment]
If you run into any problems, please feel free to reopen and I'll look into it.

**Comment by rumpelsepp** [comment]
Oh. I forgot to report :D. It works, thanks for implementing it!
