### ISSUE TITLE
Support something similar to `json.RawMessage`

### ISSUE THREAD

**Issue by kostko** [fxamacker/cbor#11]
It would be nice if this library supported something similar to [`json.RawMessage`](https://golang.org/pkg/encoding/json/#RawMessage) which could be used to delay decoding of a field.

**Comment by fxamacker** [comment]
Thanks for the suggestion.  I'll look into it.

**Comment by fxamacker** [comment]
Commit 1a2918702e980f0776663d11290dfe40e20a8c08 added support for RawMessage, Marshaler, and Unmarshaler.

Please try it and let me know what you think.

**Comment by kostko** [comment]
Nice, thanks for the quick implementation, looks good!

**Comment by fxamacker** [comment]
No problem.  This feature is useful and I already used it in one of my projects today!

**Comment by fxamacker** [comment]
@kostko I released [v1.2.0](https://github.com/fxamacker/cbor/releases/tag/v1.2.0) with this feature and more.  

It includes 2 tests using intentionally malformed CBOR data from [oasis-core tests](https://github.com/oasislabs/oasis-core/blob/master/go/common/cbor/cbor_test.go).  

Thanks for using this library!
