### ISSUE TITLE
Simultaneous toarray and omitempty question

### ISSUE THREAD

**Issue by ZenGround0** [fxamacker/cbor#113]
Hey @fxamacker 👋

I am evaluating using this library for a [cryptocurrency network client](https://github.com/filecoin-project/go-filecoin).  Other than a general liking to your high level tradeoffs, the big thing that brought me here was the `toarray` feature for tuple-encoding structs.  

Another feature that isn't supported that is potentially in my requirements list is an `omitempty` tag used on the field of a struct decorated with `toarray`.  Depending on how this requirement shakes out I may become interested in opening a PR to add this feature to your library.  Is this feature something you would consider as an improvement in light of the project's tradeoffs?  Would you accept such a PR?

Thanks!

**Comment by fxamacker** [comment]
Hi @ZenGround0, 

I'd love to see this library used by go-filecoin!

I'd like to hear more about the combination of `toarray` and `omitempty` struct tags.

I see two scenarios (one seems risky, other is interesting):
* risky: if any struct fields are omitted because they're empty, then the position of each encoded array element cannot be used to identify them by the decoder.

* interesting: if the entire struct marked as `toarray` is to be omitted when all its fields are empty, then that is a clever way for a CBOR protocol to produce more compact data.  Very nice! :smile:

Are there different scenarios you had in mind?

p.s.  I've been working on adding CBOR tags (major type 6) so if your requirements need that, please share details about that aspect as well!

**Comment by ZenGround0** [comment]
> Risky: If any struct fields are omitted because they're empty, then the position of each encoded array element cannot be used to identify them by the decoder.

Thanks for this.  Upon more reflection this is pretty clearly a bad idea and the requirement has shifted so feel free to close out this issue.

> ...please share details about that aspect as well.

We are only using one tagged datatype and I didn't have any problems adding the bytes directly to a custom `(Un)MarshalCBOR` method. 

This tagged type has a `(Un)MarshalBinary` method which means this library almost works automatically on objects of the type.  Since tags were still unsupported when I first wrote this I had no choice but to define a custom wrapper/alias and write/read tag bytes myself.  However I am suspicious I will be in the same situation even after the tag support lands as I likely won't be able to modify the type.  So one thing that would be quite helpful for my use case but likely out of scope of what you want to build is the ability to tag an external type that can't be changed so that tag bytes are automatically read and written during (de)serialization.

**Comment by fxamacker** [comment]
@ZenGround0 I may have some good news unless I misunderstood. I'll use the term tag item (major type 6) to mean tag number + tag content.

Are you using (Un)Marshaler interfaces to read/write tag numbers and (Un)MarshalBinary to decode/encode tag content?

> However I am suspicious I will be in the same situation even after the tag support lands as I likely won't be able to modify the type. 

What do you mean by "modify the type"?

> So one thing that would be quite helpful for my use case but likely out of scope of what you want to build is the ability to tag an external type that can't be changed so that tag bytes are automatically read and written during (de)serialization.

That sounds like a key feature of v2.1 so it's not out of scope unless I misunderstood.

* Feb 2, 2020 - release v2.0 (new API, faster speed, use less memory)
* Feb 9, 2020 - release v2.1 (CBOR tags major type 6, optimizations for decoding)

In API v2.1, a simple use case of CBOR tags works like this:
* If you register a user-defined Go type with tag number(s), then library automatically:
  * verifies tag number during decoding
  * writes tag number during encoding 
  * decode/encode tag content as in v1, including (Un)MarshalBinary if implemented

So you don't need to code (Un)Marshaler interface unless you need custom transformation of CBOR tag item (tag number + tag content).

Does this match your use case?  I'd love to get your feedback even if a decision was/is made to use another library.  Thanks!

**Comment by ZenGround0** [comment]
> Does this match your use case?

Nice, I think it does. To make sure:
> If you register a user-defined Go type with tag number(s)

Does registering that type require defining a field or method on that type?  Or can I simply pass the type / an instance into a registration function?  If it is the later than this is just what I'm looking for.

**Comment by fxamacker** [comment]
> Does registering that type require defining a field or method on that type?

:tada: It only requires defining a Go type.  Library forbids registering tags to native types like `int`.

In the following examples, MyFloat is registered to tag number 123.  MyFloat doesn't have fields or methods.  

EncMode and DecMode are interfaces with immutable options and tags.  They are reusable and safe for concurrent use.  See #117 for a quick summary of v2.0 API.

Example v2.1 (decoding with CBOR tag):
```
type MyFloat float64

// Register tag number 123 with tag content type MyFloat
...
tags.Add(reflect.TypeOf(MyFloat(0.0)), 123) 

// Create reusable DecMode with immutable tags & options.
dm := cbor.DecOptions{}.DecModeWithTags(tags)

// Decode CBOR data into instance of MyFloat type.  
// Tag number is verified to match registered tag number of MyFloat.
var v MyFloat
err := dm.Unmarshal(b, &v)
```

Example v2.1 (encoding with CBOR tag):
```
type MyFloat float64

// Register tag number 123 with tag content type MyFloat
...
tags.Add(reflect.TypeOf(MyFloat(0.0)), 123) 

// Create reusable EncMode with immutable tags & options.
em := cbor.EncOptionsPreferredUnsorted().EncModeWithTags(tags)

// Encode MyFloat into []byte.
// Tag number written is the one(s) registered for MyFloat.
var v MyFloat
b, err := em.Marshal(v)
```

Encoding will write tag number 123 and decoding will verify tag number matches what was registered for MyFloat.

To show one way to save space, MyFloat used options that encode values from  
float64-->float32-->float16 if values fit.
