### ISSUE TITLE
Add encoding options for time values that are uninitialized

### ISSUE THREAD

**Issue by x448** [fxamacker/cbor#121]
By default, v2.0 will encode uninitialized time.Time values to CBOR null.

Option for different ways to encode these may be added to v2.1 or v2.2.

I asked for guidance at https://github.com/cbor-wg/CBORbis/issues/167.  

I also mistakenly posted this issue over there (good grief, too many tabs.)

**Comment by x448** [comment]
By default v2.1 should encode uninitialized time.Time values as:
* CBOR Null if encoding options specify time shoudn't be tagged (default)
* CBOR float16 NaN (0x7e00) if encoding options specify time values must be tagged

In terms of providing other options that override this default, it's probably best to hold off until 7049bis or at least people working on it provide more guidance.

**Comment by x448** [comment]
I'm leaning toward this one because it provides shortest form and 7049bis section 5.7:
>In some CBOR-based protocols, the simple value (Section 3.3) of Undefined might be used by an encoder as a substitute for a data item with an encoding problem, in order to allow the rest of the enclosing data items to be encoded without harm.

* CBOR Null if encoding options specify numeric or string time shouldn't be tagged (default)
* CBOR Undefined if encoding options specify numeric time values must be tagged
* CBOR Undefined if encoding options specify string time values must be tagged

CBOR Null = we know it's a zero-value and we are saying so with CBOR Null
CBOR Undefined = we know it's a zero-value but you wanted it tagged which is undefined

**Comment by fxamacker** [comment]
We'll hold off on this issue until 7049bis is approved.  For now, we'll encode as @x448 specified in #151.

**Comment by x448** [comment]
There's bigger fish to fry, lets close this and reduce clutter.  We're encoding to CBOR Null to avoid interop issues between CBOR and JSON as mentioned by Laurence Lundblade.
