### ISSUE TITLE
Add decoding options for duplicate map keys

### ISSUE THREAD

**Issue by x448** [fxamacker/cbor#122]
Unless I'm mistaken, this looks like the only missing major feature (for some apps) after v2.1.

**Comment by x448** [comment]
@fxamacker, here you go from draft v2.1 docs update.  Probably way too much for your commit msg.  It's for the Standards section so it starts off a bit too pedantic. (ignore the first 1-2 sentences)

__Duplicate Map Key Options__

This library provides options for fast detection and rejection of duplicate map keys based on applying a Go-specific data model to CBOR's extended generic data model in order to determine duplicate vs distinct map keys. Detection relies on whether the CBOR map key would be a duplicate "key" when decoded and applied to the user-provided Go map or struct. 

`DupMapKeyQuiet` turns off detection of duplicate map keys. It tries to use a "keep fastest" method by choosing either "keep first" or "keep last" depending on the Go data type.

`DupMapKeyEnforcedAPF` enforces detection and rejection of duplidate map keys. Decoding stops immediately and returns `DupMapKeyError` when the first duplicate key is detected. The error includes the duplicate map key and the index number. 

APF suffix means "Allow Partial Fill" so the destination map or struct can contain some decoded values at the time of error. It is the caller's responsibility to respond to the `DuplicateMapKeyErr` by discarding the partially filled result if that's required by their protocol.

**Comment by fxamacker** [comment]
Closed by commit e882cb5e44b60bf9cc4f014667899382029bd9ed.
