### ISSUE TITLE
Decoder should reject CBOR non-array data for structs decorated with "toarray"

### ISSUE THREAD

**Issue by ZenGround0** [fxamacker/cbor#129]
I found what seems to be a small bug or at least a behavior that is different than I expected.  When attempting to decode cbor map bytes into a struct decorated with `toarray`, `Unmarshal` does not return an error, instead opting to treat the the `toarray` struct as a map and silently return a struct with 0 valued fields.

This behavior is nothing I can't work around if it is intentional, but it seems more intuitive to treat `toarray` decorated structs as arrays on decode so that `Unmarshal` behaves the same way on them as it would on an array type.

<details>
  <summary>Expand for related code stub</summary>
 This stub is written in terms of my own thin wrappers around Marshal and Unmarshal as well as the testify assert/require library but hopefully conveys the point.

```golang
type arrStruct struct {
	_ struct{} `cbor:",toarray"`
	Field1 int
	Field2 string
}

type mapStruct struct {
	Num    int    `json:"num"`
	Mesage string `json:"mesage"`
}

func TestOutBlockDecode(t *testing.T) {
	var out arrStruct

	// encode a cbor int
	i := 88
	bi, err := encoding.Encode(i)	
	require.NoError(t, err)

	// encode a bad array
	arr := []string{"a", "b", "dddd"}
	barr, err := encoding.Encode(arr)	
	require.NoError(t, err)

	// encode a cbor map
	m := mapStruct{5, "words"}
	bm, err := encoding.Encode(m)	
	fmt.Printf("map bytes: %x\n", bm)
	require.NoError(t, err)

	// Attempt decode (all should error)
	err = encoding.Decode(bi, &out)
	require.Error(t, err)
	fmt.Printf("err: %s\n", err)

	err = encoding.Decode(barr, &out)	
	require.Error(t, err)
	fmt.Printf("err: %s\n", err)

	var other []int
	err = encoding.Decode(bm, &other)	
	require.Error(t, err) // putting map bytes into []int errors as expected
	fmt.Printf("err: %s\n", err)

	err = encoding.Decode(bm, &out)	
	require.Error(t, err) // no error putting map bytes into array struct
	fmt.Printf("err: %s\n", err)
}
```
</details>

**Comment by fxamacker** [comment]
Great catch.  I will have a fix soon.

Unmarshal() should return UnmarshalTypeError when decoding CBOR non-array data to structs tagged with "toarray".

**Comment by x448** [comment]
Hey @ZenGround0 you mentioned using thin wrappers -- I hope v2.0 released last night makes it easier to maintain them.  At a glance:

__API__

In v2.0, functions with identical signatures to encoding/json include:
`Marshal`, `Unmarshal`, `NewEncoder`, `NewDecoder`, `encoder.Encode`, `decoder.Decode`.

API for EncMode interface, which can be created from EncOptions struct:
```
// EncMode interface uses immutable options and is safe for concurrent use.
type EncMode interface {
	Marshal(v interface{}) ([]byte, error)
	NewEncoder(w io.Writer) *Encoder
	EncOptions() EncOptions  // returns copy of options
}
```

__Usage__
```
// Create EncOptions using either struct literal or a function.
opts := cbor.CanonicalEncOptions()

// If needed, modify encoding options
opts.Time = cbor.TimeUnix

// Create reusable EncMode interface with immutable options, safe for concurrent use.
em, err := opts.EncMode()   

// Use EncMode like encoding/json, with same function signatures.
b, err := em.Marshal(v)
// or
encoder := em.NewEncoder(w)
err := encoder.Encode(v)
```

If default options are acceptable, then EncMode or DecMode don't need to be created.  Package-level codec funcs have same signatures too.

Updated [API](https://github.com/fxamacker/cbor/#api) and [Usage](https://github.com/fxamacker/cbor/#usage) today with more info about this -- and godoc will be updated this week.
