### ISSUE TITLE
chore: create issue templates for bug rpt, feature req, doc/wiki/website issue, and security issue disclosure

### ISSUE THREAD

**Issue by x448** [fxamacker/cbor#135]
Make it easier for people to report issues or contribute in other ways.

- [x] new issue template to report bugs
- [x] new issue template for feature requests
- [x] new issue template about using the library
- [x] new issue template to report security issues
- [ ] update Contribution guidelines (make it more concise)

**Comment by x448** [comment]
I came across an interesting scenario: https://github.com/containerd/containerd/pull/4014

After v2.1 or v2.1 it could be useful to have contributor guidelines mention specific requirements:
* code contributions to the core library (maybe require signing, email & real name like containerd)
* text-only changes to README.md (does not require signing, can be anonymous)

Also, the contributor guidelines initially inspired by that C++ JSON library should probably be updated to be more concise.

**Comment by fxamacker** [comment]
Issue templates are done.

![image](https://user-images.githubusercontent.com/33205765/76673126-511fc300-6570-11ea-8c13-596427eb1fdc.png)
