### ISSUE TITLE
Feedback wanted for upcoming v2.1 CBOR tags API

### ISSUE THREAD

**Issue by fxamacker** [fxamacker/cbor#136]
__UPDATED (Feb. 5, 2020 10:51 PM CST)__:  added new functions `DecModeWithSharedTags` and `EncModeWithSharedTags` in "API Related to CBOR Tags"

:new: A shared TagSet can be used as a tag registry and any EncMode created with it using EncModeWithSharedTags will automatically use updated tags.

<hr>

I'd like to release v2.1 with support for CBOR tags (major type 6) around Feb 9, 2020.

Your feedback/questions would be appreciated.  Please feel free to point out anything I missed.  

Terms used:  
* tag = tag number + tag content.
* TagSet = Go interface representing a collection of registered tag number + Go type + tag options.

:point_right: There's no reduction in functionality related to how tag content is encoded or decoded between v1.5 and v2.1.  Underlying floats will use their options, BinaryMarshaler and etc. are still supported.

:point_right: EncMode and DecMode are interfaces created from EncOptions and optionally TagSet.  During mode creation, EncOptions and TagSet are copied into private immutable representations.

EncMode and DecMode are meant to be reused, free from side-effects (changes to TagSet, etc.), and fast/safe for concurrency.  

There's no global tag registry but TagSet can be reused to create multiple EncMode and DecMode interfaces.

<details>
  <summary>v2.0 - Six Codec Funcs that Will Never Change + SemVer for Other Funcs</summary><p>

After v2.0, these six codec funcs will __never change__ their signatures and are same as encoding/json:  
`Marshal`, `Unmarshal`, `NewEncoder`, `NewDecoder`, `encoder.Encode`, `encoder.Decode`

Funcs other than the above six comply with SemVer 2.0 unless marked as "subject to change".

Functions marked "subject to change" are:
* CoreDetEncOptions() -- uses draft RFC not yet approved by IETF (est. "later 2020")
* PreferredUnsortedEncOptions() -- uses draft RFC not yet approved by IETF (est. "later 2020")

</details>

<details>
  <summary>v2.0 - API of EncMode interface</summary><p>

EncMode interface can be created from EncOptions struct:

```
// EncMode interface uses immutable options and is safe for concurrent use.
type EncMode interface {
    Marshal(v interface{}) ([]byte, error)
    NewEncoder(w io.Writer) *Encoder
    EncOptions() EncOptions  // returns copy of options
}
```
</details>

<details>
  <summary>v2.0 - Usage of EncMode interface and EncOptions struct</summary><p>
  
```
// Create EncOptions using either struct literal or a function.
opts := cbor.CanonicalEncOptions()

// If needed, modify encoding options
opts.Time = cbor.TimeUnix

// Create reusable EncMode interface with immutable options, safe for concurrent use.
em, err := opts.EncMode()   

// Use EncMode like encoding/json, with same function signatures.
b, err := em.Marshal(v)
// or
encoder := em.NewEncoder(w)
err := encoder.Encode(v)
```

If default options are acceptable, then EncMode or DecMode don't need to be created.  Package-level codec funcs have same func signatures.

@x448 updated [API](https://github.com/fxamacker/cbor/#api) and [Usage](https://github.com/fxamacker/cbor/#usage) some more after 2.0 release.
</details>

<details>
  <summary>v2.1 - API Related to CBOR Tags</summary><p>

```
type Tag struct {
    Number  uint64
    Content interface{}
}

type RawTag struct {
    Number  uint64
    Content RawMessage
}

type TagOptions struct {
    DecTag DecTagMode // DecTagIgnored, DecTagOptional, DecTagRequired 
    EncTag EncTagMode // EncTagIgnored, EncTagRequired
}

type TagSet interface {
    Add(opts TagOptions, tagContentType reflect.Type, tagNum uint64, nestedTagNum ...uint64) error
    Remove(tagContentType reflect.Type)
    ...
}

func NewTagSet() TagSet 

// DecModeWithTags creates DecMode having immutable copy of TagSet
func (opts DecOptions) DecModeWithTags(tags TagSet) (DecMode, error) 

// DecModeWithSharedTags creates DecMode having a shared TagSet
// Changes to TagSet will automatically be used by DecMode
func (opts DecOptions) DecModeWithSharedTags(tags TagSet) (DecMode, error) 

// EncModeWithTags creates EncMode with given tags
func (opts EncOptions) EncModeWithTags(tags TagSet) (EncMode, error) 

// EncModeWithSharedTags creates EncMode having a shared TagSet
// Changes to TagSet will automatically be used by EncMode
func (opts EncOptions) EncModeWithSharedTags(tags TagSet) (EncMode, error) 
```
</details>

<details>
  <summary>v2.1 - How to register user-defined Go type with tag number</summary><p>

```
// User defined type can be on array, float64, int64, map, slice, struct, and etc.
type MyFloat float64

// Create TagSet.
tags := NewTagSet()

// Register MyFloat type with tag number 123
tags.Add(
    TagOptions{DecTag: DecTagRequired, EncTag: EncTagRequired},
    reflect.TypeOf(MyFloat(0.0)), 
    123)

// Create EncMode interface
em, err := EncOptions{ShortestFloat: cbor.ShortestFloat16}.EncModeWithTags(tags)

// Encode MyFloat value. It'll be tagged 123 and encode using shortest float.
myFloatBytes, err := em.Marshal(MyFloat(4.56))

// Create DecMode interface
dm, err := DecOptions{}.DecModeWithTags(tags)

// Decode MyFloat value
var f MyFloat
err = dm.Unmarshal(myFloatBytes, &f)

// Modifying TagSet won't affect already-created EncMode or DecMode.
// This is done to reduce side-effects and simplify concurrency.
```

Encoder will write tag number 123 and decoder will verify tag number matches what was registered for MyFloat.  TagOptions can be set to modify this.

</details>

<details>
  <summary>v2.1 - How to encode Go value with tag number</summary><p>

This is a one-time encoding for a tag number and tag content.  It can be used for encoding tag number with values (not types). For example int64 can't be registered (not user-defined type) so this can be used on an int64 value.

Use `Tag` to encode tag number and `interface{}`.
```
taggedFloat := Tag{Number: 123, Content: float64(4.56)}
b, err := cbor.Marshal(taggedFloat)
```

Use `RawTag` to encode tag number and `cbor.RawMessage`.
```
rawMessage := cbor.RawMessage([]byte{131, 2, 3, 4})
taggedRawMessage := RawTag{Number: 123: Content: rawMessage}
b, err := cbor.Marshal(taggedRawMessage)
```

</details>

<details>
  <summary>v2.1 - How to extract tag number from CBOR tag</summary><p>

Use `Tag` to extract tag number and decode tag content to interface{}
```
var tag Tag
err := cbor.Unmarshal(b, &tag)
```

Use `RawTag` to extract tag number and decode tag content to cbor.RawMessage
```
var rawTag RawTag
err := cbor.Unmarshal(b, &rawTag)
```

</details>

Thanks @x448 for v2.0 & v2.1 API ideas.
cc @kostko @ZenGround0

**Comment by kostko** [comment]
I think the API looks good, my only comment would be around the TagSet and EncMode/DecMode. 
> There's no global tag registry but TagSet can be reused to create multiple EncMode and DecMode interfaces.

I assume one would want to avoid re-creating an EncMode/DecMode on every encoding/decoding operation as it seems to copy the TagSet? So the best way to have a tag registry would be to keep a synchronized EncMode/DecMode around and regenerate it whenever the TagSet is updated?

**Comment by fxamacker** [comment]
Great point!  My (bad?) theory was TagSet would rarely or never change at runtime in most scenarios.  And multiple EncMode would be created at startup with different settings.

> want to avoid re-creating an EncMode/DecMode on every encoding/decoding

Yes, EncMode and DecMode are best when reused and long-lived.  TagSet is also safe for concurrent use.

:new: __EncOptions{}.EncModeWithMutableTags()__  
If we limit mutability to TagSet, enough of EncMode could be reused to limit bloat.  It would still be slower for tagged encoding/decoding compared to immutable EncMode.

:point_right: EncMode interface could export `ReplaceTagSet` and it would return error if EncMode wasn't created with `EncOptions{}.EncModeWithMutableTags()`

```
type EncMode interface {
    ...
    ReplaceTagSet(TagSet)  // new func
}

(EncOptions) EncMode() (EncMode, error)
(EncOptions) EncModeWithTags() (EncMode, error)
(EncOptions) EncModeWithMutableTags() (EncMode, error) // new func
```

>  keep a synchronized EncMode/DecMode around and regenerate it

Do you know if sync.atomic is possible & appropriate to replace old EncMode interface with new?  

Please let me know your preferences and any suggestions.  Thanks!

**Comment by x448** [comment]
Maybe add func to return whether EncMode was created (1) w/o tags, (2) w/ tags,  (3) w/ mutable tags.

**Comment by kostko** [comment]
> My (bad?) theory was TagSet would rarely or never change at runtime in most scenarios

This theory is actually not bad ;-) However the most likely use will be that types are registered from package `init()` handlers and you don't know when all init handlers are done. You could expect users to run a "freeze tagset" in `main()`, but this doesn't seem all that nice. It could also be annoying during tests where test types could be registered at runtime.

> Do you know if sync.atomic is possible & appropriate to replace old EncMode interface with new?

Hm, I'll think about this some more tomorrow.

**Comment by x448** [comment]
@fxamacker maybe provide `EncModeWithSharedTags(TagSet)` plus what you mentioned about making EncMode & TagSet able to be initialized without init() based on kostko's last comment?  

:new: EncOptions{}.EncModeWithSharedTags(TagSet)
* Users can decide if they want their shared TagSet instance to be a global var.  
* Users would call tag registration functions on shared TagSet instead of EncMode.
* Updates to shared TagSet would be used by EncMode without extra steps if created with EncModeWithSharedTags(TagSet).

This would also make docs easier than distinguishing mutable vs immutable everywhere.  If OK, then update API in this issue and ask everyone?

Super glad kostko provided feedback and hope he continues.  :+1:

**Comment by fxamacker** [comment]
I updated the top post based on kostko's feedback with x448.  Here are the key changes so far:

:new: A shared TagSet can be used as a tag registry and any EncMode created with it using EncModeWithSharedTags will automatically use updated tags.

__v2.1 will provide 3 ways to create EncModes__:
* EncMode() has no tag support.
* EncModeWithTags(TagSet) creates EncMode with immutable copy of TagSet's data.
* EncModeWithSharedTags(TagSet) creates EncMode with shared TagSet (it will directly use it.)

__EncOptions{...}.EncModeWithSharedTags(TagSet)__
* Users can decide if they want a shared TagSet instance to be a global var.
* Users can Add/Remove tags from TagSet -- TagSet is also safe for concurrency.
* Updates to a shared TagSet would be used automatically by any EncMode created with EncModeWithSharedTags and that specific TagSet.

__Initialization Won't Require init()__

<details>
  <summary>Example initializing TagSet and EncMode outside init().
  </summary><p>

```
var (
	tagSet     = registerTags()
	encMode, _ = cbor.CanonicalEncOptions().EncModeWithTags(tagSet)
)

type MyFloat float64

func registerTags() cbor.TagSet {
	tags := cbor.NewTagSet()
	tags.Add(
		cbor.TagOptions{DecTag: cbor.DecTagRequired, EncTag: cbor.EncTagRequired},
		reflect.TypeOf(MyFloat(0.0)),
		123,
	)
	return tags
}

func init() {
	fmt.Printf("encMode: %+v\n", encMode.EncOptions())
}
```

</details>

Please let me know whether this works for you or any other feedback.  Thanks!

**Comment by kostko** [comment]
Cool thanks, this looks good to me!

**Comment by fxamacker** [comment]
Closing this now, but feel free to add feedback.
