### ISSUE TITLE
Unsupported CBOR negative int values should return error

### ISSUE THREAD

**Issue by x448** [fxamacker/cbor#14]
As documented under Limitations section, CBOR negative integers like -18446744073709551616 are unsupported because they cannot fit into Go's int64.

But instead of returning 0 with err=nil, I think cbor.Unmarshal should return an error when trying to decode these values.

Go's encoding/json handles this scenario by returning json.UnmarshalTypeError.  So this library should probably return cbor.UnmarshalTypeError.

**Comment by fxamacker** [comment]
I agree.  

Commit 47055e770d43a9920be073d7f62c47b72011ed8c closes this issue.
