### ISSUE TITLE
Backport v2.0 fix to v1.5 (sanitize decoded NaN and Infinity time values)

### ISSUE THREAD

**Issue by x448** [fxamacker/cbor#141]
This was resolved in v2.0 #120 by the decoder treating CBOR NaN and Infinity time values as if they were CBOR Null.  

Also update godoc overview to point to v2.x releases and encourage projects to upgrade.

CBOR RFC 7049 specified the same tag number to allow integer and float content representing time.  By comparison, MessagePack avoided float while still supporting nanosecond time resolution with their unsigned integer timestamp "tag" (extension).

**Comment by fxamacker** [comment]
Closed by commit 19c21f85d9c2bc9f86fa34b7e308e7814c8e9f31.

This is being fuzzed by @x448 and it is expected to hit required execs within 30 hours (he's using a slow server and v1 is slower than v2 for fuzzing).

This will be released as v1.5.1 after fuzzing.

**Comment by x448** [comment]
Fuzzing passed 288,718,805 execs for v1.5.1 on Feb 8.
