### ISSUE TITLE
chore: Benchmarks should use parallelism provided by Go's testing pkg

### ISSUE THREAD

**Issue by x448** [fxamacker/cbor#146]
One advantage of v2.x is faster parallelism when using EncMode and DecMode with immutable options & tags.  Enough of this advantage remains when using shared (mutable) TagSet.

https://golang.org/pkg/testing/#B.RunParallel

**Comment by x448** [comment]
@fxamacker Do you want to add this to 2.3.0 or close this?

Milestone 2.3 doesn't have a lot of features planned (maybe not enough features to even justify the fuzz-testing overhead of a release at this point).

**Comment by fxamacker** [comment]
I'll add this to milestone 2.3 but others will need to benchmark at various CPU counts for me until I upgrade or buy an extra machine for benching & optimizing work.

I like having low watts & tdp but I also wish I could bench and optimize using 1, 2, 4, 8, and 16 physical cpu cores with proper bios settings and non-gui os to see it gracefully scale to 16.

It'll be interesting to see especially with relevant improvements underway in golang/go (hopefully released in Go 1.15)!

**Comment by x448** [comment]
I have additional things in mind for benchmarks.  Probably best as a separate project to reduce bloat.
