### ISSUE TITLE
Safe optimization for COSE (RFC 8152) and WebAuthn

### ISSUE THREAD

**Issue by x448** [fxamacker/cbor#15]
It would be nice to be able to decode **CBOR maps with integer keys** to Go struct, and vice versa.

This feature would speed up and simplify using this library for COSE.  It would also speed up WebAuthn since that uses COSE.

**Comment by fxamacker** [comment]
Thanks.  I'll look into it for v1.3.0.

**Comment by fxamacker** [comment]
Decoding COSE to struct is 42.125% faster than decoding to map[int]interface{} and 42.105% less B/op.  

Benchmarks of decoding COSE to map[int]interface{} vs. struct:

```
BenchmarkDecodeCOSE/COSE_to_Go_map[int]interface_{}-2                         	 1000000	      1600 ns/op	     456 B/op	      13 allocs/op
BenchmarkDecodeCOSE/COSE_to_Go_cbor_test.coseKey-2                            	 2000000	       926 ns/op	     264 B/op	      13 allocs/op
```
