### ISSUE TITLE
Replace example CBOR program in size comparison chart

### ISSUE THREAD

**Issue by x448** [fxamacker/cbor#16]
Program size comparison should use existing 3rd-party program(s), instead of one you wrote for solely for comparison.

If you want, I'll give it a shot and post result(s) here.  I'll find IoT and security related projects because they value size, safety and reliability.

Let me know.

**Comment by fxamacker** [comment]
Sounds good to me!

**Comment by x448** [comment]
I'll tackle this using v1.3 when released.  

Nice work on the CBOR decoding speedup after v1.2 in commit 726c4236fd0fcf0805db7287323b21a8c6995747. Looking forward to the other CBOR speedups planned for v1.3.

**Comment by x448** [comment]
Some of the projects I'm finding don't pass their existing tests before I make any changes :angry:!   Or they support other serialization like MessagePack using the competing library, so it would be apples to oranges comparison if I remove that.

**Comment by x448** [comment]
I found a non-hobby project using CBOR with Go that doesn't require installing c libraries, etc.   

Replacing the library they use with fxamacker/cbor __saves 4 MB in their compiled program size__.

I'll look for a simpler example that requires less coding change but at least there's one real-world example for comparison.

Please add this issue to next milestone.

**Comment by x448** [comment]
@fxamacker you already know so you can skip reading this. It's here to keep track for new comparison charts.

cisco/senml program sizes would shrink from by 4 MB by switching to this library, judging by it's built-in programs senmlCat and senmlServer. 

[Disco SenML](https://github.com/x448/senml) was created to demo this debloating but it ended up fixing several other open issues.  E.g. it fixes their CBOR representation not using integers for labels as required by SenML RFC 8428.  It also has a smaller attack surface.

**Comment by fxamacker** [comment]
The CBOR speed and program size comparison charts look great.  I didn't expect this library to be faster because the other library uses `unsafe` and code gen!  

Having senmlCat for program size comparison was a good idea.

Thanks for doing these comparisons!
