### ISSUE TITLE
docs: Fix go.dev and README compatibility

### ISSUE THREAD

**Issue by fxamacker** [fxamacker/cbor#173]
__UPDATE__:  v2.2 was released a few minutes before midnight on Feb 24, 2020 with only some (less than half) of the README.md markdown tables replaced by SVG tables.  go.dev has rendering bugs and doesn't provide a "refresh" button so it was frustrating on Saturday having to wait until Sunday to see if changes look OK.  And then waiting for go.dev again on Sunday night.

<hr>

All 10-12 tables in README.md are still not rendering properly on go.dev.

@x448 We should fix this ASAP so v2.2 can be tagged as soon as fuzzing hits required execs.

Here's a separate repo so we don't have to release tag this project each time README is updated to see if it worked.

GitHub: https://github.com/fxamacker/godev
  
go.dev: https://pkg.go.dev/github.com/fxamacker/godev?tab=overview

Issue on golang/go for go.dev: https://github.com/golang/go/issues/37284
Issue on golang/go for go.dev: https://github.com/golang/go/issues/37394

**Comment by x448** [comment]
I'm not optimistic about this getting resolved by go.dev.  We need to find a solution that doesn't rely on them doing the right thing.

**Comment by x448** [comment]
I'm no longer optimistic about getting a constructive response abouut go.dev if all we've gotten so far is "offending table" as the only piece of info we can use to resolve the problem.

I really miss the old Go team and the old "Do No Evil" Google.

**Comment by x448** [comment]
I'm no longer optimistic about getting a timely and constructive response about go.dev if all we've gotten so far is "offending table" as the only piece of info we can use to resolve the problem.

I really miss the old Go team and the old "Do No Evil" Google.

**Comment by x448** [comment]
I think turning all 12 tables of text into images is probably not a great idea, especially on top of existing images.

Converting all the tables into SVG might be the best long-term solution especially if they can be embedded inside the README.md and not difficult to keep updated using a text editor.  I don't know yet if GitHub and go.dev supports embedded SVG.  Also, it would involve testing on IE.

I'm sorry this wasn't wrapped up over the weekend.  I know you wanted to release and announce v2.2 this morning.

**Comment by x448** [comment]
I can convert the first 3 tables into SVG tonight so we can still release v2.2 today to get the bug fix out since it affects all versions.

BTW, I saw apache/trafficcontrol almost migrated to fxamacker/cbor this weekend but they went back to json because they cannot upgrade to Go 1.12 without breaking something unrelated that needs investigation.  I don't know when they'll try again because they're at 4.0.0-RC.

**Comment by x448** [comment]
OK, first three tables are finally converted to SVG, try it out on your godev repo and see if they render fine at go.dev.

HOWEVER, I think I need to modify them again for the font-family to have more than just Roboto.

**Comment by x448** [comment]
It looks like a repeat of Saturday when we couldn't get go.dev to grab the latest release of your godev repo.  And then it appeared on Sunday without any further action on our part.

**Comment by fxamacker** [comment]
go.dev finally picked up the latest release of godev repo.  The svg tables look great!  I tested using Firefox on Fedora.

**Comment by x448** [comment]
@fxamacker It's impossible for anyone outside go.dev to fix any prior versions.  The only version we can "fix" by converting to SVG is the latest version released.  They have the sole power to fix rendering problems of all prior releases they show on go.dev.

I don't know enough about SVG and I don't remember the last time I used a drawing tool before helping with README on this project.  In other words, the Encoding Options table shown below isn't going to be a lunchtime conversion to SVG for me (I'm sure UX people can).

So the good news I'll just simplify it a lot and it'll probably look a lot nicer and easier to read.  The bad news is users can't copy/paste a setting from the table into CTRL-F to read more details (in the same number of steps they can with markdown tables).

| Encoding Option | Available Settings (defaults in bold, aliases in italics) |
| --------------- | --------------------------------------------------------- |
| EncOptions.Sort | __`SortNone`__, `SortLengthFirst`, `SortBytewiseLexical`, _`SortCanonical`_, _`SortCTAP2`_, _`SortCoreDeterministic`_ |
| EncOptions.Time | __`TimeUnix`__, `TimeUnixMicro`, `TimeUnixDynamic`, `TimeRFC3339`, `TimeRFC3339Nano` |
| EncOptions.TimeTag | __`EncTagNone`__, `EncTagRequired` |
| EncOptions.ShortestFloat | __`ShortestFloatNone`__, `ShortestFloat16` |
| EncOptions.InfConvert | __`InfConvertFloat16`__, `InfConvertNone` |
| EncOptions.NaNConvert | __`NaNConvert7e00`__, `NaNConvertNone`, `NaNConvertQuiet`, `NaNConvertPreserveSignal` |
| EncOptions.IndefLength | __`IndefLengthAllowed`__, `IndefLengthForbidden` |
| EncOptions.TagsMd | __`TagsAllowed`__, `TagsForbidden` |

**Comment by fxamacker** [comment]
Thanks.  What you showed me earlier looks better than markdown!

**Comment by x448** [comment]
I agree it looks nicer but ...

Imagine a user seeing a specific setting in the intro section, searching for it with CTRL-F and it isn't found.  What contributed to this brain-fart is bringing up .svg files directly in the browser outside the img tag which let me interact with it like regular html content.

 I'll see if we can use `<object>` instead of `<img>` to see if it helps.

**Comment by x448** [comment]
@fxamacker I think we can close this because all the affected markdown tables were converted to svg.

We still need to avoid using non-breaking space and non-breaking hyphens -- at least  
until https://github.com/golang/go/issues/37394 is fixed.

**Comment by fxamacker** [comment]
Agreed!
