### ISSUE TITLE
feature: Add decoding option to be more strict than encoding/json: fail on CBOR map if destination struct field is not found

### ISSUE THREAD

**Issue by kostko** [fxamacker/cbor#178]
Currently any unknown fields are skipped during decoding, would it be possible to have an option to fail instead?

**Comment by fxamacker** [comment]
I think so.  Just to make sure:

```
type MyStruct struct {
    A: string
    B: string
    C: string
}
```

1. OK if CBOR map is {"A": a, "B": b, "C": c} -- field by field match, same sort order not required.

2. OK if CBOR map is {"A": a, "B": b} -- CBOR map is a subset.

3. Err if CBOR map is {"A": a, "B": b, "C": d, "D": d} -- Go struct is a subset.  Stop decoding.

Is this what you have in mind?

**Comment by kostko** [comment]
Yes, this was my idea.

Although thinking about it, there can be cases where you would want other constraints, e.g., for ensuring canonical round-tripping you would need to reject non-canonical sort orders, different ways of encoding the same type, etc. (also see https://github.com/oasislabs/oasis-core/issues/2020).

**Comment by fxamacker** [comment]
Great!  The issue you linked to is appreciated and I've bookmarked it so I can refer to it while dealing with important issues it raised.

Thanks for continuing to make really useful feature requests!

**Comment by x448** [comment]
@fxamacker we should document that by default, this library tries to behave like `encoding/json` for scenarios like this (should make a list).  

And then document (when implemented) that it offers options like the one proposed in this issue to be more strict than `encoding/json`.

**Comment by x448** [comment]
https://golang.org/pkg/encoding/json/#Decoder.DisallowUnknownFields

> func (dec *Decoder) DisallowUnknownFields()
>
> DisallowUnknownFields causes the Decoder to return an error when the destination is a struct and the input contains object keys which do not match any non-ignored, exported fields in the destination.

**Comment by fxamacker** [comment]
@kostko this feature was added in commit 37a0c7ee5134fde9cab8c2f2435bd2da89c9efcf

Please let me know if it works for you: https://play.golang.com/p/Gy8WgtuaFH0

**Comment by kostko** [comment]
Looks good, thanks!
