### ISSUE TITLE
docs:  make CBOR features table (svg) wide enough for SF Pro Text font

### ISSUE THREAD

**Issue by x448** [fxamacker/cbor#183]
I made a mistake by not realizing I had Roboto installed on a Mac, so the text fit in the columns when I did a quick visual check.

The svg then got updated to vectorize the checkmark to resolve an issue on very old Android devices but used a font-family that put SF Pro Text first (previously Roboto).

Fix this by either embedding Roboto.woff or shorten the text & widen the table.

**Comment by fxamacker** [comment]
Fixed in PR by @x448 in another repo.
