### ISSUE TITLE
Add to cbor.io

### ISSUE THREAD

**Issue by rumpelsepp** [fxamacker/cbor#2]
I created a pull request to add your library to cbor.io. There are a few open questions you might be more qualified to answer than me: https://github.com/cbor/cbor.github.io/pull/56#issuecomment-520320334

Please jump in. :-)

**Comment by fxamacker** [comment]
Hi,

Thanks for recommending this project.  I missed this until today.

I commented in the thread and hopefully it is helpful.

Thanks again,

Faye

**Comment by x448** [comment]
It seems the delay isn't whether to add this library to cbor.io, the delay is whether to replace an already listed library with this one.

None of the Go implementations listed on cbor.io support "preferred serialization" which encodes both integers and floats to their smallest forms (like float16).

**Comment by x448** [comment]
@fxamacker congrats on this project getting listed on cbor.io today! :tada:  The lucky person who wanted his project listed today got in on the same day and triggered a bunch of updates to cbor.io.

**Comment by fxamacker** [comment]
@rumpelsepp Your PR was merged into cbor.io today!  It was very nice of you to do this.  Thank you so much!
