### ISSUE TITLE
docs: Private member struct tag (json:"-" and cbor:"-") are supported but not documented.

### ISSUE THREAD

**Issue by jkralik** [fxamacker/cbor#201]
**Is your feature request related to a problem? Please describe.**
I want to have option to set member of struct as private. For json encoder/decoder you can do it with tag `json:"-"`.

**Describe the solution you'd like**
Implement support for tag `json:"-"`.
- For encoder member is not marshaled to cbor.
- For decoder value is not modified during unmarshaling,

**Comment by x448** [comment]
@fxamacker this looks like a useful feature to have.

A scenario for using this is described in "Ignoring Private Fields" at:
https://www.digitalocean.com/community/tutorials/how-to-use-struct-tags-in-go

cc @jkralik

**Comment by fxamacker** [comment]
@jkralik thanks for using this library and reporting this!

Good news is this feature is currently supported, but not yet documented.  I will document this in README and in source code.

Both `json:"-"` and `cbor:"-"` tags work.  If both are specified, "cbor" tag is used.

Please let me know if it works for you.  

```
type S struct {
	A int
	B int
	C int `json:"-"`
}

// Encode struct s with private field
s := S{A: 1, B: 2, C: 3}
wantBytes := hexDecode("a2614101614202") // {A: 1, B: 2}
b, err := Marshal(s)
if err != nil {
	t.Errorf("Marshal(%+v) returned error %v", s, err)
} else if !bytes.Equal(b, wantBytes) {
	t.Errorf("Marshal(%+v) returned 0x%x, want 0x%x", s, b, wantBytes)
}

// Decode b to struct s with private field
b = hexDecode("a3614101614202614303") // {A: 1, B: 2, C: 3}
s = S{}
wantS := S{A: 1, B: 2}
err = Unmarshal(b, &s)
if err != nil {
	t.Errorf("Unmarshal(0x%x) returned error %v", b, err)
} else if !reflect.DeepEqual(s, wantS) {
	t.Errorf("Unmarshal() returned %+v, want %+v", s, wantS)
}
```

**Comment by jkralik** [comment]
Yes. It is worked - just update doc. The my issue is: https://github.com/fxamacker/cbor/issues/204
