### ISSUE TITLE
chore: CI should test more Go versions when actions/setup-go fixes performance issue

### ISSUE THREAD

**Issue by x448** [fxamacker/cbor#203]
GitHub's ubuntu-latest image recently started to include 4 versions of Go (1.11.x - 1.14.x).  However, actions/setup-go downloads and installs Go if any version != 1.14 is specified.

The preinstalled Go versions can be leveraged by GitHub's setup/go so it won't cause a 10 sec delay during CI for each specified version of Go.  

If and when the following setup/go issue is fixed, use the matrix feature of GitHub Workflow Actions to test the latest 3 versions of Go:

https://github.com/actions/setup-go/issues/39

**Comment by fxamacker** [comment]
Looks like actions/setup-go#39 got fixed!  🎉
