### ISSUE TITLE
bug: Decode replace struct type by map

### ISSUE THREAD

**Issue by jkralik** [fxamacker/cbor#204]
### What version of fxamacker/cbor are you using?
2.2

### Does this issue reproduce with the latest release?
yes

### What OS and CPU architecture are you using (`go env`)?
playground

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?

https://play.golang.org/p/Ap2EYTZkrAk

### What did you expect to see?

Don't replace it.

### What did you see instead?

It's retuns map type instead of struct.

**Comment by x448** [comment]
By comparison, Go's encoding/json also replaces struct type with map type in the same scenario.

Example using fxamacker/cbor:
https://play.golang.org/p/Ap2EYTZkrAk
> main.S before unmarshal
> map[interface {}]interface {} after unmarshal

Example using encoding/json (only 2 lines modified to use json):
https://play.golang.org/p/lO7sVRp0iB2

> main.S before unmarshal
> map[string]interface {} after unmarshal

cc @fxamacker

**Comment by fxamacker** [comment]
Both fxamacker/cbor and encoding/json can avoid this issue if you change two lines of code.

@jkralik  please let me know if this works for you.  @x448 thanks for encoding/json example.

```
//n := reflect.New(reflect.TypeOf(s)).Elem().Interface()
  n := reflect.New(reflect.TypeOf(s)).Interface()
//err := cbor.Unmarshal(data, &n)
  err := cbor.Unmarshal(data, n)
```

Example using fxamacker/cbor:
https://play.golang.org/p/RWLxBqHEzNX

Example using encoding/json:
https://play.golang.org/p/ajKSF1WJ8qk

**Comment by jkralik** [comment]
Yes it works. I used before ugorji/codec and the issue wasn't there. Thx for help.

**Comment by fxamacker** [comment]
Yes that is correct, ugorji/codec handles this example differently than encoding/json.

By default, I try to make fxamacker/cbor behave like encoding/json and then provide options for non-default behavior. For example, #178 will be in the next release.

Thanks for opening issues, confirming solution, and also providing new info.  :+1:

Please let me know if you run into any other issues or questions.  If you have questions that don't fit into issue templates, feel free to open questions as a documentation bug.
