### ISSUE TITLE
feature: convert CBOR to JSON (and vice versa) with unknown content

### ISSUE THREAD

**Issue by jdbruijn** [fxamacker/cbor#206]
### What version of fxamacker/cbor are you using?
`v2@v2.2.0`

### Does this issue reproduce with the latest release?
Yes.

### What OS and CPU architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/jdebruijn/.cache/go-build"
GOENV="/home/jdebruijn/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/jdebruijn/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/linuxbrew/.linuxbrew/Cellar/go/1.14/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/linuxbrew/.linuxbrew/Cellar/go/1.14/libexec/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc-5"
CXX="g++-5"
CGO_ENABLED="1"
GOMOD="/home/jdebruijn/withthegrid/projects/platform-dtls-termination-proxy/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build852627047=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

See my (hopefully minimalistic) example code here.

https://play.golang.org/p/5YMin1Qw6kI

I've got some code that is acting as a proxy. At the one side (client) I exclusively communicate in CBOR and at the other side (server) I exclusively communicate in JSON. Therefore, I need to convert CBOR to JSON and vice versa. During these conversions, the content can be anything, so I have no knowledge over the object that is being transferred. I don't need to do anything with the content, so if there is a way to make these conversions without first creating the 'native' objects, please let me know.

As far as I can see there are 2 issues with the conversion from JSON to CBOR.
1. The numbers are converted to floats.
    I've played around with the `EncOptions` a bit and searched through the docs and examples, but coudn't get it working as I expect. I do see a difference between the size of the encoded number when I add and use the different `ShortestFloat` options. Nonetheless, it always stays a float.
2. The datetime is not converted as datetime format (tag 1).
   The datetime is a string in the CBOR object. I've tried playing around with the `EncOptions` for `Time` and some of the tag related options, but it always kept being a string.

I don't even know if this is the correct approach to do this conversion so am also very open to pointers to a different approach if there is a better one!
Also: this is the first time I'm using this library and I'm relatively new to Go, so maybe I'm overlooking something very obvious too :p Any help would be greatly appreciated.

I think I've got the conversion of CBOR to JSON ([playground](https://play.golang.org/p/QXYT09Z5S47)) except for a separate issue with the datetime.

### What did you expect to see?
1. I expected for the numbers to be converted as integers.
2. I expected the date to be converted to a timestamp item (tag 1).

### What did you see instead?
1. The numbers are converted to floats.
2. The date is a string.

**Comment by x448** [comment]
@jdbruijn thanks for opening this issue.

Given the code snippet doing:  

JSON --> `encoding/json` --> `interface{}` --> `fxamacker/cbor` --> CBOR

We should expect:

A. When interface{} contains Go time.Time value, fxamacker/cbor outputs CBOR datetime.

B. When interface{} contains Go string value, fxamacker/cbor outputs CBOR text string.

Unfortunately, there appears to be a limitation in encoding/json when decoding to interface{}, so encoding/json does this:
* JSON number -> Go float64
* JSON datetime -> Go string

When Go float64 and Go string are given to fxamacker/cbor, it correctly encodes them to CBOR floating-point and CBOR text string. 

The best solution would be to use a JSON decoder that can decode JSON datetime strings to Go time.Time and etc. when decoding to Go interface{}.  

Normally, I wouldn't suggest this but your issue is so well-written I think you might have a better shot than most of us at convincing Go team to add this as an option to the decoder in encoding/json.

@fxamacker can you take a look in case I missed anything?

**Comment by jdbruijn** [comment]
@x448 Thanks a lot for the elaborate reply.

I now understand that this is not an issue with CBOR, but rather with `encoding/json`. I also found the Go [JSON specification](https://blog.golang.org/json) that states the types that it uses for conversions (which obviously don't include `int` and `datetime`.

I'll continue my quest for a JSON encoder/decoder that works like I want and might create an issue for this in the Go repo. Thanks for pointing me in the right directions!

BTW: Great job on the documentation on this library! Looks real nice!

**Comment by jdbruijn** [comment]
For anyone running into this issue I thought I share my results here.
I've solved/worked around the issue by creating a function that standardises a JSON interface. Hope this helps anyone! BTW I've also got a bunch of unit tests of this code if anyone is interested just let me know and I can share those too.

```go
package app

import (
	"math"
	"reflect"
	"regexp"
	"time"
)

// StandardiseJSONInterface standardises certain entities in a given JSON
// interface.
//
// This function is intended to be used on interfaces returned by encoding/json
// `Unmarshal` function. On this interface, this function will perform the
// standardisations listed below.
// - If a string is found that matches the specific date format described below,
//   that string is converted to `time.Time`.
//   The only supported format is `YYYY-MM-DDTHH:mm:ss.sssZ`, which is a
//   simplified ISO 8601 format. This is the specific format that the Javascript
//   `Date.prototype.toISOString()` returns.
// - If a number (float64) is found that has a fractional part of exactly zero,
//   that number is converted to an iteger (int64).
//
// The numbers that can be safely represented are numbers between -(2^53 - 1)
// and 2^53 - 1. This is because the numbers in the object are first converted
// to the Go type `float64`, which is a double-precision 64-bit binary format
// IEEE 754 value. This format can only safely represent integer numbers within
// the range described above.
func StandardiseJSONInterface(obj interface{}) interface{} {
	value := reflect.ValueOf(obj)

	switch value.Kind() {
	case reflect.Float64:
		item := value.Float()

		// It the item can be truncated and is still the same, that means that there
		// is truncated part had no significance and the item can be safely
		// represented by an integer number.
		// `9007199254740991` is the IEEE 754 largest positive double precision
		// integer number (2^53 -1).
		integer, _ := math.Modf(item)
		if math.Abs(integer) <= float64(9007199254740991) && item == integer {
			if math.Signbit(item) {
				return int64(item)
			}
			return uint64(item)
		}

	case reflect.String:
		match, _ := regexp.MatchString(
			`^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z$`, value.String())
		if match {
			t, err := time.Parse(time.RFC3339, value.String())
			if err == nil {
				return t
			}
		}

	case reflect.Slice:
		returnSlice := make([]interface{}, value.Len())
		for i := 0; i < value.Len(); i++ {
			returnSlice[i] = StandardiseJSONInterface(value.Index(i).Interface())
		}
		return returnSlice

	case reflect.Map:
		tmpData := make(map[string]interface{})
		for _, k := range value.MapKeys() {
			tmpData[k.String()] = StandardiseJSONInterface(
				value.MapIndex(k).Interface())
		}
		return tmpData
	}

	return obj
}
```

**Comment by jdbruijn** [comment]
@rbolkey Glad it helped and thanks for sharing your experience. To not spam this ticket too much, let's continue the conversation here: https://gist.github.com/jdbruijn/09ba26d13a603128960eb5747a60014c
