### ISSUE TITLE
CBOR security comparisons should include newer malformed CBOR data that cause "fatal error: runtime: out of memory"

### ISSUE THREAD

**Issue by x448** [fxamacker/cbor#208]
CBOR security comparison table only compares fxamacker/cbor to ugorji/go 1.1.7 -- update it to compare with all released versions of ugorji/go using newer malformed CBOR data.

The old comparison uses two malformed CBOR samples found in September 2019 (https://github.com/oasislabs/oasis-core/issues/2153) that affects ugorji/go 1.1.6 & 1.1.7 but not all of the older versions.  

Newly discovered malformed CBOR samples of tiny size (smaller than "hello world") is confirmed to cause `fatal error: runtime: out of memory` in these versions of ugorji/go (with only 1 decode attempt required):

* :fire: ugorji/go 42bc974 (Aug 12, 2019 -- latest commit)
* :fire: ugorji/go 1.1.7 (Jul 2, 2019 -- latest release)
* :fire: ugorji/go 1.1.6 (Jul 2, 2019 -- same release date as 1.1.7)
* :fire: ugorji/go 1.1.5-pre (May 28, 2019)
* :fire: ugorji/go 1.1.4 (Apr 8, 2019)
* :question: ugorji/go 1.1.3 (not found on GitHub)
* :fire: ugorji/go 1.1.2 (Jan 26, 2019)
* :fire: ugorji/go 1.1.1 (Apr 9, 2018)
* :fire: ugorji/go 1.1 (Jan 21, 2018 -- first non-beta release)

Separately, an unrelated project claims to have encountered `fatal: morestack on g0` with malformed CBOR when decoded with ugorji (presumably 1.1.4) but I've not confirmed that one yet.

@fxamacker I'll submit PR updating the comparisons using the new CBOR samples you found and confirmed.  Thanks for discovering these, running tests on each version to confirm and making sure fxamacker/cbor properly rejects these new CBOR samples.

**Comment by x448** [comment]
@fxamacker please confirm the new benchmarks using malformed CBOR data that causes "fatal: out of memory" error in all released versions of ugorji/go.

This will replace the old security comparison table which only mentions ugorji/go 1.1.7 instead of all versions.

fxamacker/cbor 2.2
```
2020a   59.8 ns/op     32 B/op   1 allocs/op        // March 2020 data
2020b  149.0 ns/op    128 B/op   3 allocs/op        // March 2020 data
```

**Comment by fxamacker** [comment]
@x448 confirmed. I had to test more versions of ugorji/go with 2020b so both samples are confirmed to cause "fatal: out of memory" error in all releases of ugorji/go.  Benchmarks match what I gave you.

The last commit of ugorji/go is also confirmed to have "fatal: out of memory" error with these 2 data.

**Comment by x448** [comment]
@fxamacker thanks for the merge, the README.md shows the updated security comparison table and slideshow using new malformed CBOR data you found in March 2020.

**Comment by x448** [comment]
@fxamacker exact message is "fatal error: out of memory" and not "fatal: out of memory", correct?

**Comment by fxamacker** [comment]
@x448 I'm sorry, the error message I gave to you initially is incorrect.  

Exact error message for both samples is  
"fatal error: runtime: out of memory".

**Comment by x448** [comment]
@fxamacker please update the SVG files to show the correct error message.  

Alternatively, create new malformed data that causes the shorter fatal error message if that is easier for your (i have no preference).

**Comment by fxamacker** [comment]
@x448 fixed error messages in SVG file with commit fxamacker/images@3ab25f3abad8d6662eac5b2c8748fcb27dcd5153.

**Comment by x448** [comment]
Updated slideshow to show correct fatal error msg.  Closing.
