### ISSUE TITLE
chore: linters badge shows "failure" and GitHub Actions Workflow results dont appear on last pull request.

### ISSUE THREAD

**Issue by x448** [fxamacker/cbor#212]
UPDATE:  Not sure but it appears GitHub may have had problems this Sunday that caused workflow results to not appear on the last PR (but it appeared in prior PR, earlier on Sunday).  

<hr>

@fxamacker linters badge.svg is showing "failure" because `go fmt` wasn't run on doc.go yesterday.

More importantly, the last pull request for doc.go doesn't display any workflows running.  So workflows actually ran but stopped showing up on the pull request.

### What did you expect to see?

The last pull request should show various GitHub Actions Workflow running.

### What did you see instead?

None of the GitHub Actions Workflow results appear in the pull request.

However, the "linters: failing" badge showed up on the README.md because the workflows actually ran without showing up on the pull request.

### Next steps

I'll look into workflow configs by reviewing past pull requests and seeing when workflow results stopped appearing.  Maybe it got broken last time GitHub Actions Workflow files got updated.

@fxamacker if you want, update doc.go with `go fmt` so "linters: failing" badge turns into "linters: passing" while I look into workflows.  Thanks.

**Comment by x448** [comment]
The PR prior to the last one correctly shows a green check, and clicking on the check shows a popup with the workflow results.

So I'm inclined to think there may have been a GitHub issue this weekend (Sunday).

![image](https://user-images.githubusercontent.com/57072051/78589044-3524df80-7805-11ea-80d2-224224b46162.png)

**Comment by x448** [comment]
The commit properly shows a small :x: and clicking on the :x: pops up the 4 workflow results.

![image](https://user-images.githubusercontent.com/57072051/78590478-859d3c80-7807-11ea-9eb4-73f10b9494fc.png)

**Comment by x448** [comment]
Nothing weird when clicking on Details for linters workflow.

![image](https://user-images.githubusercontent.com/57072051/78590968-50451e80-7808-11ea-959c-8e1230f9d744.png)

**Comment by x448** [comment]
Unless we can reproduce this, I think it was a temporary GitHub problem on Sunday.

**Comment by fxamacker** [comment]
@x448 It's working again with the latest PR.  It looks like a github problem.

![image](https://user-images.githubusercontent.com/33205765/78591720-8040f180-7809-11ea-838e-31e735a561bc.png)
