### ISSUE TITLE
feature: support marshal/unmarshall to io.ReadWriter

### ISSUE THREAD

**Issue by ddevault** [fxamacker/cbor#215]
**Is your feature request related to a problem? Please describe.**
This is a bit of an edge case, perhaps, but I would like to support streaming CBOR fields from external sources. For example, I'd like a particular field of a CBOR structure to be populated from a network request, and populate it gradually by fetching data from the network as necessary - never having the entire file in memory.

**Describe the solution you'd like**
One approach to this would be to support marshalling and unmarshalling to io.ReadWriter. If unmarshalling, only Read operations would be valid, and vice versa.

**Describe alternatives you've considered**
Another option would be an incremental encoder/decoder, but it would be more difficult to use.

**Comment by fxamacker** [comment]
Hey @ddevault, to help me understand better, can you provide:
* Go code example/psuedocode using the new API
* for each new API, describe input, output, and side-effects (if any)
* describe relevant data types/sizes/structures and their encodings (including data from external source)

Thanks!

**Comment by ddevault** [comment]
I apologise for the noise - after further research it seems CBOR isn't suited to my use-case after all.
