### ISSUE TITLE
bug: decoding should ignore CBOR tag number 55799 when it is a prefix

### ISSUE THREAD

**Issue by fxamacker** [fxamacker/cbor#228]
### What version of fxamacker/cbor are you using?

v2.2.0

### Does this issue reproduce with the latest release?

yes

### What OS and CPU architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?

Decode CBOR tag item with tag number 55799 to a Go interface{} (empty interface).

### What did you expect to see?

The empty interface populated by the tag content.

### What did you see instead?

The empty interface populated by a `cbor.Tag` struct which contains both tag number and tag content.

This is appropriate behavior for all unrecognized CBOR tags, but tag 55799 is a special case.  Ignoring it and simply decoding the tag content into the empty interface would be the correct default behavior.

### Notes

When decoding CBOR tag item with tag number 55799 to Unmarshaler, UnmarshalCBOR should receive tag content only.  

UnmarshalCBOR should receive the same CBOR data whether it is tagged with tag number 55799 or not.

see also: #227 and https://github.com/cbor-wg/CBORbis/issues/183.

**Comment by x448** [comment]
I asked 7049bis for clarification regarding tag 55799.

```
Consider this CBOR data:

tag number 0 <-- time tag
tag number 55799 <-- normally an error to have tag here, but tag 55799 is normally ignored
tag content <-- time value

How should a generic decoder handle the data?
A. always invalid, since tag 0 doesn't expect another tag
B. always valid, since tag 55799 is a no-op that should be ignored
C. allow the CBOR-based protocol to specify either A or B

If the answer is C, then which of A or B does 7049bis prefer when CBOR-based protocol
doesn't specify?
```

**Comment by fxamacker** [comment]
@x448 thanks.  I updated the issue to only strip tag number 55799 when it is a prefix. 

I'll close this issue today with a commit that has been fuzz testing since yesterday.  It reached 214 million execs.

Before making additional changes to handle non-prefix scenarios, I'll wait for clarification to your question from 7049bis.
