### ISSUE TITLE
Audit library for any missing attribution for code snippets from Go's stdlib (encoding/json)

### ISSUE THREAD

**Issue by fxamacker** [fxamacker/cbor#233]
Issue #232 mentioned isEmpty() helper function is the same as encoding/json.  

I noticed isEmpty() is missing a comment attributing the Go stdlib.  Fix this by adding a comment to isEmpty() and audit the library to correct similar issues (if any).

Example of a modified function that mentions original function:

https://github.com/fxamacker/cbor/blob/bffaf0cda7c548af6e819cd5385f025bb6fee6f8/structfields.go#L85-L86

**Comment by x448** [comment]
In the meantime, update copyright notice in README.md and LICENSE as described in #234.

After that, update the copyright notice immediately below yours in each source code file if required.

**Comment by x448** [comment]
Can you please audit the code for any snippet that may be from any other projects besides Go standard library?
