### ISSUE TITLE
bug: `DecOptions.ExtraReturnErrors` field should be typed

### ISSUE THREAD

**Issue by Yawning** [fxamacker/cbor#240]
There's some minor type related inconsistencies with the newly added `DecOptions.ExtraReturnErrors` field and the associated constants.  

 * `ExtraDecErrorNone` is typed (`ExtaDecErrorCond`).
 * `ExtraDecErrorUnknownField` is untyped.
 * `maxExtraDecError` is an int.
 * `DecOptions.ExtraReturnErrors` is an int.

Consequently, it is not possible to use `ExtraDecErrorNone` without a cast right now.

**Comment by fxamacker** [comment]
Thanks for reporting this.  I'll look into it.

**Comment by fxamacker** [comment]
@Yawning commit bafca87fa6db74480aced7f106869a58376cc664 fixed this issue.

`DecOptions.ExtraReturnErrors` field type is changed to `ExtaDecErrorCond`, same type as its associated constants `ExtraDecErrorNone`, `ExtraDecErrorUnknownField`, and `maxExtraDecError`.  No type casting is needed.

Please let me know if it works for you.

**Comment by kostko** [comment]
Looks good, thanks for the fix!
