### ISSUE TITLE
feature: allow for decoding of unknown types

### ISSUE THREAD

**Issue by david415** [fxamacker/cbor#241]
Is it currently possible to decode an unknown CBOR type?
That is to say, with prior knowledge of a set of possible encoded types, is it possible to decode the CBOR blob without knowing which type it is?

I'm using CBOR for a wire protocol where each CBOR blob is length prefixed. However the CBOR blobs are of unknown type... but they are certainly of one of the types in a known set of types. What I want is somewhat akin to the golang switch type assertion.

**Comment by fxamacker** [comment]
@david415 thanks for opening this issue.

> Is it currently possible to decode an unknown CBOR type?

Yes.  You can decode CBOR data to empty interface `interface{}` and then use type switch to handle different types.  

### Decoding tagged CBOR data to empty interface

CBOR tag is tag number + tag content.  Tag number is a positive integer.  Tag content is an encoded CBOR blob.  Tag number is used to give tag content additional meaning.  In this case, you can use tag number to indicate encoded type.

When decoder is registered with tag number and Go type, **decoder decodes tagged CBOR data to registered Go type**.  

```
// Create TagSet with tag number and Go type
tags := cbor.NewTagSet()
err := tags.Add(
    cbor.TagOptions{EncTag: cbor.EncTagRequired, DecTag: cbor.DecTagRequired},
    reflect.TypeOf(MyType{}),    // your custom type
    MyTypeCBORTagNumber,         // CBOR tag number for your custom type
)

// Create decoding mode with TagSet	
dm, err := cbor.DecOptions{}.DecModeWithTags(tags)

// Decode unknown CBOR blob
var v interface{}
err = dm.Unmarshal(b, &v) 
  
// Use type switch to handle different types
switch v := v.(type) {
case MyType:  // custom type
    ...
default:
    ...
}
```

### Decoding not tagged CBOR data to empty interface

**Decoder decodes not tagged CBOR data to boilerplate Go types**.  Please refer to [Unmarshal documentation](https://godoc.org/github.com/fxamacker/cbor#Unmarshal) for more details.

```
// Decode unknown CBOR blob
var v interface{}
err := cbor.Unmarshal(b, &v)

// Use type switch to handle different types
switch v := v.(type) {
case []interface{}:                // boilerplate Go type for CBOR array
    ...
case map[interface{}]interface{}:  // boilerplate Go type for CBOR map
    ...
default:
    ...
}
```

> I'm using CBOR for a wire protocol where each CBOR blob is length prefixed. However the CBOR blobs are of unknown type... but they are certainly of one of the types in a known set of types. What I want is somewhat akin to the golang switch type assertion.

Many CBOR based protocols, such as COSE and CWT, use CBOR tags to flag content types.  I think it would be easier and cleaner if CBOR tags can be used in this case.

Please let me know if it works for you.

**Comment by david415** [comment]
Thanks! That first code example was exactly what I was looking for. I did recently make my code work with a wrapping struct type... but using tags is certainly a lot nicer. I think we can close this ticket since it sufficiently documents how to use this feature.

**Comment by omerfirmak** [comment]
Hey @fxamacker,

I am trying to reproduce what you described here.

``` golang
type Transaction struct {
	Value any
}

func transactionCBORTags() (cbor.TagSet, error) {
	ts := cbor.NewTagSet()

	types := []struct {
		reflectType reflect.Type
		txType      TransactionType
	}{
		{
			reflect.TypeOf(DeclareTransaction{}),
			Declare,
		},
		{
			reflect.TypeOf(DeployTransaction{}),
			Deploy,
		},
		{
			reflect.TypeOf(InvokeTransaction{}),
			Invoke,
		},
	}

	for _, aType := range types {
		err := ts.Add(
			cbor.TagOptions{EncTag: cbor.EncTagRequired, DecTag: cbor.DecTagRequired},
			aType.reflectType,
			// https://www.iana.org/assignments/cbor-tags/cbor-tags.xhtml
			// 65536-15309735 	Unassigned
			65536+uint64(aType.txType),
		)
		if err != nil {
			return ts, err
		}
	}

	return ts, nil
}

func (t *Transaction) MarshalCBOR() ([]byte, error) {
	if tags, err := transactionCBORTags(); err != nil {
		return nil, err
	} else if enc, err := cbor.CanonicalEncOptions().EncModeWithTags(tags); err != nil {
		return nil, err
	} else {
		return enc.Marshal(t.Value)
	}
}

func (t *Transaction) UnmarshalCBOR(data []byte) error {
	if tags, err := transactionCBORTags(); err != nil {
		return err
	} else {
		dec, err := cbor.DecOptions{}.DecModeWithTags(tags)
		if err != nil {
			return err
		}

		return dec.Unmarshal(data, t.Value)
	}
}
```

But after `UnmarshalCBOR` t.Value ends up being a `cbor.Tag` I was expecting it to be one of the types in `transactionCBORTags`. Am I missing something here? Thanks!

```
expected: core.Transaction(core.Transaction{Value:core.DeployTransaction{ContractAddressSalt:(*felt.Felt)(0xc0000d8ba0), ContractAddress:(*felt.Felt)(0xc0000d8b80), Class:core.Class{APIVersion:(*felt.Felt)(nil), Externals:[]core.EntryPoint(nil), L1Handlers:[]core.EntryPoint(nil), Constructors:[]core.EntryPoint(nil), Builtins:[]*felt.Felt(nil), ProgramHash:(*felt.Felt)(nil), Bytecode:[]*felt.Felt(nil)}, ConstructorCallData:[]*felt.Felt{(*felt.Felt)(0xc0000d8bc0), (*felt.Felt)(0xc0000d8be0), (*felt.Felt)(0xc0000d8c00), (*felt.Felt)(0xc0000d8c20), (*felt.Felt)(0xc0000d8c40)}, CallerAddress:(*felt.Felt)(0xc0000d8c60), Version:(*felt.Felt)(0xc0000d8c80)}})
actual  : cbor.Tag(cbor.Tag{Number:0x10001, Content:map[interface {}]interface {}{"CallerAddress":[]interface {}{0x0, 0x0, 0x0, 0x0}, "Class":map[interface {}]interface {}{"APIVersion":interface {}(nil), "Builtins":interface {}(nil), "Bytecode":interface {}(nil), "Constructors":interface {}(nil), "Externals":interface {}(nil), "L1Handlers":interface {}(nil), "ProgramHash":interface {}(nil)}, "ConstructorCallData":[]interface {}{[]interface {}{0xda916bfd882dd42b, 0x9c4585d186f2d4bd, 0x71cba698f15a4fed, 0xc751deb1d413e6}, []interface {}{0xc797bef5653f44fa, 0x666b58474fbd32e8, 0x3d1f703ac6cac73c, 0x1d82c96c08a21fc}, []interface {}{0xffffffffffffffc1, 0xffffffffffffffff, 0xffffffffffffffff, 0x7fffffffffffbd0}, []interface {}{0x7e8bf9c0391cdecd, 0xa9b31a178fffc54c, 0x934c56ec03a4ab9b, 0x29b690d37e1ca7a}, []interface {}{0x369c9ec7d94a62c7, 0x5eab02988056eccf, 0x8ea4c24f310eead3, 0x19d74d80d073ec1}}, "ContractAddress":[]interface {}{0x3def68e3f99fba4d, 0x259a461dbe85aef7, 0xd573b8811ab8727d, 0x761cb960196403a}, "ContractAddressSalt":[]interface {}{0xc99f9d6ecf083ff1, 0xc676a0d2f3c398f9, 0xf78347edfd46d8ab, 0x1e1149897d65d99}, "Version":[]interface {}{0x0, 0x0, 0x0, 0x0}}})
```

**Comment by omerfirmak** [comment]
Got it working [this](https://github.com/NethermindEth/juno/pull/541) way
