### ISSUE TITLE
docs: share test for ugorji/go failing 

### ISSUE THREAD

**Issue by ugorji** [fxamacker/cbor#247]
### What is the URL of the content?

https://github.com/fxamacker/cbor/blob/master/README.md

### Please describe the problem.

I am @ugorji , author of github.com/ugorji/go/codec . 

I saw your page with the issue listed that the codec library didn't handle malformed input well.

I will love to narrow down that issue and fix it in codec.

Can you please share the tests or raise an issue on my github page, with a reproducer?

Thank you.

### Screenshot (if applicable).

https://raw.githubusercontent.com/fxamacker/images/master/cbor/v2.2.0/cbor_security_table.svg

**Comment by kostko** [comment]
Some starting points:
* https://github.com/fxamacker/cbor-fuzz
* https://github.com/oasisprotocol/oasis-core/blob/01ce036d695a5b98075cc90f8063c93802b18f9c/go/common/cbor/cbor_test.go#L10-L24

**Comment by ugorji** [comment]
@kostko I ran those 2 tests, and received the expected errors. 

The fuzz is not a good reproducer for me. 

Can you share the tests which can reproduce the "out of memory" issues. That's a very serious problem if it exists, and I must get to the bottom of it before it affects production systems.

Thanks.

**Comment by kostko** [comment]
Those two test cases were found by fuzzing, just note that this was a while back (Sep 2019) so maybe the issues got fixed in go-codec since then. In any case, I suggest you fuzz go-codec.

Related issues:
* https://github.com/oasisprotocol/oasis-core/issues/2153
* https://github.com/fxamacker/cbor/issues/208

**Comment by fxamacker** [comment]
I think the suggestion about fuzzing is the way to go.  The reproducers provided by kostko in his related issues are useful too.
