### ISSUE TITLE
question: Encoding a single data item or an array of 2 or more data values

### ISSUE THREAD

**Issue by thomas-fossati** [fxamacker/cbor#250]
This is not an issue, it's just a question that I'm asking to the community of this wonderful Go package.

Context: I'm implementing [CoSWID](https://www.ietf.org/archive/id/draft-ietf-sacm-coswid-15.html), whose CDDL is sprinkled with things like:
```
directory => directory-entry / [ 2* directory-entry ]
[...]
label => text / int / [ 2* text ] / [ 2* int ]
```
Basically all arrays that contain only one element are supposed to be encoded as the underlying type (be it a scalar or compound).

Has any of you already dealt with a similar situation?  Do you see a solution that avoids going `interface{}` all the way and would allow instead preserving some sort of type structure on the Go side?

TIA!

**Comment by thomas-fossati** [comment]
Looks like something like the following should do the trick:
```
import (
	cbor "github.com/fxamacker/cbor/v2"
)

type Files []File

func (fa Files) MarshalCBOR() ([]byte, error) {
	if len(fa) == 1 {
		return cbor.Marshal(fa[0])
	}

	return cbor.Marshal([]File(fa))
}

func (fa *Files) UnmarshalCBOR(data []byte) error {
	if (data[0] & 0xe0) == 0x80 {
		return cbor.Unmarshal(data, (*[]File)(fa))
	}

	var f File

	if err := cbor.Unmarshal(data, &f); err != nil {
		return err
	}

	*fa = append(*fa, f)

	return nil
}
```

**Comment by fxamacker** [comment]
Thanks for bringing up an interesting use case and providing a solution!

> Basically all arrays that contain only one element are supposed to be encoded as the underlying type (be it a scalar or compound).

I believe you have the right solution to handle a mix of scalar and array types.  You may need to do the same trick to handle a mix of int and text types.

This can be a useful feature for other users as well.  I'll think about it more and I might add it to this library.

BTW, are you working on a reference implementation for CoSWID?

**Comment by thomas-fossati** [comment]
> I believe you have the right solution to handle a mix of scalar and array types. You may need to do the same trick to handle a mix of int and text types.

For "union" fields like `rel`, `use`, `version-scheme` and `ownership` I'm currently wrapping an `interface{}`, e.g.:
```
type Rel struct {
	val interface{}
}
```
and providing custom marshalers and unmarshalers for the type.  Since they all share the same underlying format, the encode/decode/set/check mechanics can be factored out.  I'm not sure this is the optimal solution but it seems to work OK :-)

> This can be a useful feature for other users as well. I'll think about it more and I might add it to this library.

That'd be awesome.

> BTW, are you working on a reference implementation for CoSWID?

Yes, I'm implementing SWID and CoSWID.  The plan is to release it in the next couple of weeks.

**Comment by fxamacker** [comment]
> For "union" fields like `rel`, `use`, `version-scheme` and `ownership` I'm currently wrapping an `interface{}`, e.g.:
```
type Rel struct {
	val interface{}
}
```

That works.  Another way is to use `type Rel interface{}` with custom marshaler and unmarshaler.  You may want to benchmark both approaches using your data.

> Yes, I'm implementing SWID and CoSWID. The plan is to release it in the next couple of weeks.

Please feel free to ping me when you release it.  I started reading the CoSWID draft and I'm looking forward to your implementation.

**Comment by thomas-fossati** [comment]
> Please feel free to ping me when you release it. I started reading the CoSWID draft and I'm looking forward to your implementation.

Sure, it's here: https://github.com/veraison/swid (work is still in progress).

PS: I have stolen your GitHub actions scripts, thanks you once again!
