### ISSUE TITLE
bug: Can't unmarshal in structure that contains interface field

### ISSUE THREAD

**Issue by yar-resh** [fxamacker/cbor#260]
### What version of fxamacker/cbor are you using?
v2.2.0

### Does this issue reproduce with the latest release?
Yes

### What OS and CPU architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/yaroslav/.cache/go-build"
GOENV="/home/yaroslav/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/yaroslav/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build217708215=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?
https://play.golang.org/p/JnZ6HLQyFXC

I tried to unmarshal CBOR into struct that contains interface field. That field initialized with zero value of specific type, so it should be clear for unmarshaler how to unmarshal it. A [similar code](https://play.golang.org/p/rtfSjrLaKCR) for `encoding/json` package works well, but `cbor.Unmarshal` returns error `cbor: cannot unmarshal map into Go struct field main.Outer.2 of type main.TestInterface`

### What did you expect to see?
Unmarshaled data without errors

### What did you see instead?
Error `cbor: cannot unmarshal map into Go struct field main.Outer.2 of type main.TestInterface`

**Comment by fxamacker** [comment]
Thanks for reporting this bug.  I'm looking into it.

**Comment by ChronosX88** [comment]
I faced this issue too.

**Comment by x448** [comment]
Any news after looking into this on Dec 2, 2020?

**Comment by fxamacker** [comment]
Sorry about the delay.  I know how to fix it but I need to do more optimizing and testing.

**Comment by fxamacker** [comment]
Quick update on my schedule...I added the "in progress" tag on Feb 11, then Winter Storm Uri started damaging my place.  Repairs are still ongoing and it is not yet deemed "inhabitable" by my insurance company.

My apologies for the delay.

**Comment by ChronosX88** [comment]
> Quick update on my schedule...I added the "in progress" tag on Feb 11, then Winter Storm Uri started damaging my place.  Repairs are still ongoing and it is not yet deemed "inhabitable" by my insurance company.
> 
> My apologies for the delay.

@fxamacker No worries, man. Take care of yourself!
