### ISSUE TITLE
question: using CBOR tags to efficiently encode JSON key names

### ISSUE THREAD

**Issue by kegsay** [fxamacker/cbor#262]
I have a CBOR <--> JSON converter which uses `interface{}` as the intermediate type. I would like to encode JSON key names more efficiently than this approach, which just includes the whole key name in the CBOR.

I have no idea what the shape will be for some of these JSON objects, but I do know the names of some of the keys, along with the types of the values e.g `{ "event_id": "some_string" }`. The resulting CBOR isn't particularly compact because it encodes the key name `event_id` as well as the value. I can share a `TagSet` between both sides of the converter, and I was hoping to somehow map `event_id` to a number e.g `32769`, but I'm not sure exactly how to do this with the existing `TagSet` API. The problem is that it wants a `contentType reflect.Type`, there doesn't seem to be any place to specify key names anywhere.

Is this possible, and if not how would you recommend approaching this? Thanks!

**Comment by fxamacker** [comment]
Hi @kegsay, I'm sorry about the very delayed response.  I was hoping this would be answered by others or a non-manual solution would come to mind each time I revisited this.

> Is this possible, and if not how would you recommend approaching this?

Using `TagSet` isn't the ideal way for converting map keys to more compact alternatives (smaller value or different type).  I would recommend a manual conversion between CBOR <--> JSON values for this very specific scenario.

Your manual conversion approach in [matrix-org/lb/cbor_codec.go](https://github.com/matrix-org/lb/blob/main/cbor_codec.go) is the way to go  :+1:.  I am going to close this issue but please feel free to comment or reopen if needed.
