### ISSUE TITLE
Go struct to CBOR array using `cbor:",toarray"`

### ISSUE THREAD

**Issue by fxamacker** [fxamacker/cbor#30]
This allows:
* encoding Go strcut to CBOR array.
* decoding CBOR array to Go struct.

This makes encoded data more compact and structs are easier to use.

```
	type T struct {
		_ struct{} `cbor:",toarray"` 
		A int      `cbor:",omitempty"`
		B string   `cbor:",omitempty"`
	}
```
Special field "_" is used to specify struct level options, such as "toarray".  Any value of T type is encoded as array of 2 elements.  "omitempty" is disabled by "toarray" to ensure that the same number of elements are encoded every time.  

If "toarray" is omitted, "omitempty" works just like `encoding/json`.

I came across this at https://github.com/oasislabs/oasis-core/pull/2183/commits/ade6a1bbfe6f40b5c39f8f0796b9093081709943. @yawning has the best commit messages!

**Comment by kostko** [comment]
Nice, thanks!
