### ISSUE TITLE
feature: add decoding option to specify the go type to use when decoding CBOR maps into `interface{}`

### ISSUE THREAD

**Issue by lukseven** [fxamacker/cbor#303]
When decoding CBOR to generic `interface{}`, CBOR maps are decoded as `map[interface{}]interface{}` go types. Offer a decoding option to change the go map type, e.g. to `map[string]interface{}`.

**Is your feature request related to a problem? Please describe.**
I have a server application that communicates with clients through a REST API with JSON data structures. Internally it stores those data structures encoded in CBOR for improved compactness and coding efficiency. In addition, the data structures may be manipulated server-side by plugins that expect the same data types, independent of whether the data was received through the API (unmarshaled JSON) or from server-side storage (unmarshaled CBOR).

I would like to replace ugorji/cbor with this library, but am running into problems with maps, since they are decoded to `map[interface{}]interface{}` instead of `map[string]interface{}` as provided by the json decoder.

**Describe the solution you'd like**
Add a decoding option `MapType` that specifies the go map type to use when decoding CBOR maps to `interface{}`.

```go
	// MapType specifies the go type to use during schema-less decoding of a CBOR map. 
	// Defaults to map[interface{}]interface{}.
	MapType reflect.Type
```

ugorji/cbor offers this option.

**Describe alternatives you've considered**
Run a post-unmarshal process that converts the maps. This is slow and ugly.

**Additional context**
Code snippet that shows the problem: https://go.dev/play/p/84XvSau-7Yt

An alternative implementation of this feature was previously submitted in pull request #229, but refused because it didn't follow contributor guidelines.

**Comment by fxamacker** [comment]
@lukseven Thanks for reporting this!  I'll implement this feature, it makes sense to have it.

**Comment by lukseven** [comment]
@fxamacker I had a stab at implementing this myself and found an easy, low-impact way of doing it. Hope you don't mind...

**Comment by fxamacker** [comment]
@lukseven Thanks and no worries.  Nice work!  :+1:

I implemented this before taking a look at your PR #304 and found the code to be surprisingly similar!  I'd love to have you as a contributor.  :smile:

For code contributions (not docs or yml configs), we need the following item:
>  [ ] Sign each commit with your real name and email.
Last line of each commit message should be in this format:
Signed-off-by: Firstname Lastname firstname.lastname@example.com

I'd love to merge your PR (with some very minor tweaks).  If you're not comfortable giving up anonymity, then I understand (@x448 is the same way and limits contributions to docs and CI configs).  I can merge my PR if you prefer.  Either way works for me.  Please let me know!

**Comment by lukseven** [comment]
@fxamacker while I completely agree with and support the rest of your contribution guidelines, I don't see any valid reason that would mandate a sign-off with real name and email. Maybe you can enlighten me... In any case, I will not trade in privacy for the right to contribute. I coded another small feature and have some additional ideas - I will just publish them in my fork and let you decide if you want to integrate any of them in your repo.

BTW you should mention these signing requirements in [CONTRIBUTING.md](../blob/master/CONTRIBUTING.md)

Besides all this, thank you for this well-written and well-tested library! I wish there were more projects like this!

**Comment by fxamacker** [comment]
>  I don't see any valid reason that would mandate a sign-off with real name and email. Maybe you can enlighten me...

I understand why it's not desirable.  It was recommended to me by someone more experienced in these matters to reduce risk of litigation.

Examples of other projects that require this include containerd/containerd which doesn't even allow any exceptions (not even to fix a typo in their README).  Some projects, like golang/go take it one step further and also require signing in with a Google account.

I tried to be less restrictive by making an exception for README and build scripts.

> BTW you should mention these signing requirements in CONTRIBUTING.md

You're right!  Thanks for pointing it out.  Apologies for not catching that mistake.  I'll fix it.

> Besides all this, thank you for this well-written and well-tested library! I wish there were more projects like this!

Thanks!  I really like your coding style!
