### ISSUE TITLE
question: failed to decode Signature field

### ISSUE THREAD

**Issue by TheDarkPyotr** [fxamacker/cbor#313]
### What version of fxamacker/cbor are you using?
v2.3.0

### Does this issue reproduce with the latest release?
Yes

### What OS and CPU architecture are you using (`go env`)?
OS:	Ubuntu 21.04, hirsute
CPU: Intel(R) Core(TM) i7-2600 CPU @ 3.40GHz, 64-bit, (cpu MH: 2330.102, cache size: 8192 KB)
<pre>
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/luca/.cache/go-build"
GOENV="/home/luca/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/luca/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/luca/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go-1.16"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go-1.16/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.16.2"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build425445872=/tmp/go-build -gno-record-gcc-switches"
</pre>

### What did you do?

In the client / server scenario: client side I sign a payload (in bytes) with SHA256 (from the ``crypto/ecdsa`` package) and insert the signature obtained in the Signature field of the struct ``signedCWT``. I marshal through ``cbor.Marshal (signedCWT)`` where signedCWT contains as payload the payload in bytes used to obtain the signature inserted in Signature. Sending the struct signedCWT as defined above via UDP in a single payload.
Server side, I perform the reverse process: through ``cbor.Unmarshal(payload[:n], &v)`` I retrieve the content of the struct sent by the client. The variable ``n`` indicates the number of bytes received, the variable ``v`` is the recipient of the contents of the unmarshal operation.

PROBLEM: all fields sent by the client coincide perfectly with those received by the server except the ``Signature`` field which is decoded incorrectly. Example:
Client sends:
```
sig := []byte("3045022100fd303580ee634d76c33de64cd4ad9999f128958d9341e5e01fb743210e559a8e022021f01a978600d135a08b77d84f4e75ff0052c5abdb7d92450a2a6e4aec031f4b")
//sig here is explicited for example but it's generated from ecdsa.SignASN1(rand.Reader, privateKey, hash[:]) where hash := sha256.Sum256(bytePayload)


messageSigned := signedCWT{
		Protected: []byte("Protected header"),
		Unprotected: coseHeader{
			Alg: 1,
			Kid: []byte("AsymmetricECDSA256"),
			IV:  nil,
		},
		Payload:   bytePayload,
		Signature: sig,
	}
```

Server receives:

```
messageSignedReceived := signedCWT{
		Protected: []byte("Protected header"),
		Unprotected: coseHeader{
			Alg: 1,
			Kid: []byte("AsymmetricECDSA256"),
			IV:  nil,
		},
		Payload:   bytePayload,
		Signature: receivedSig,
	}
```
Where receivedSig is <pre>0E!�05��cMv�=�Lԭ���(���A���C!U�� !�����5��w�ONu�Rū�}�E</pre>

### What did you expect to see?
I expect to get the correct decoding of the signature field, citing the above  example ``3045022100fd303580ee634d76c33de64cd4ad9999f128958d9341e5e01fb743210e559a8e022021f01a978600d135a08b77d84f4e75ff0052c5abdb7d92450a2a6e4aec031f4b``

### What did you see instead?
An unexpected and apparently unjustified coding like ``0E!�05��cMv�=�Lԭ���(���A���C!U�� !�����5��w�ONu�Rū�}�E``

N.B: I discovered the library this morning and I am still in the workaround phase, I apologize in advance in case of misinterpretation / use.

**Comment by x448** [comment]
The example code snippet contains a bug which is unrelated to fxamacker/cbor.

**Comment by TheDarkPyotr** [comment]
Thanks for the quick reply,[client](https://go.dev/play/p/1ZNub2b3TIi) and [server](https://go.dev/play/p/MnrGmMuY9Rx) respectively.
You are totally right, by eliminating a part of the superfluous code it happens that even on the client side the signature check fails but I can't understand what it is due to.

**Comment by TheDarkPyotr** [comment]
Thanks for the quick reply: removing the superfluous code I found the bug. I apologize for the uselessness of the thread.
Thanks again for the help.
