### ISSUE TITLE
question: using this library to decode data with variable structure

### ISSUE THREAD

**Issue by agaffney** [fxamacker/cbor#317]
I have some CBOR-encoded data that has a variable structure depending on other values encoded within the data. For example, a particular array could have 3 elements if the first element is `0` or only 2 elements if the first element is `1`. On top of that, the data in the other elements of that array will have a different structure depending on the first value. Is it actually possible to use this library to parse CBOR like this (without using a generic `interface {}`)?

Here is the CDDL for the data in question:

https://github.com/input-output-hk/cardano-ledger/blob/master/eras/byron/cddl-spec/byron.cddl

There are many values that use `/` to indicate "this or that", and the various possibilities for those fields will not necessarily have the same structure.

This is somewhat related to #312, but only in that it's dealing with the same data.

**Comment by fxamacker** [comment]
There are two ways of delaying decoding data depending on other data.  Each way has its own limitations.

Please let me know if either of the following two approaches work for you.

## Recommended Approach - use `cbor.RawMessage`

`cbor.RawMessage` can be used to delay decoding fields.     See `cbor.RawMessage` [example](https://github.com/fxamacker/cbor/blob/master/example_test.go#L480-L507), and  `toarray` [example](https://github.com/fxamacker/cbor/blob/master/example_test.go#L405-L433).  The limitation is data structure must be known at compile time. 

Here is some rough idea based on part of the CDDL you provided:
```
// block = [0, ebblock] / [1, mainblock]
type block struct {
	_        struct{} `cbor:",toarray"`
	typ      int
	rawBlock cbor.RawMessage // mainblock if typ is 0, ebblock if typ is 1
}

/*
mainblock = [ "header" : blockhead
            , "body" : blockbody
            , "extra" : [attributes]
            ]
*/
type mainblock struct {
	_ struct{} `cbor:",toarray"`
	// mainblock fields
}

/*
ebblock = [ "header" : ebbhead
          , "body" : [+ stakeholderid]
          , extra : [attributes]
          ]
*/
type ebblock struct {
	_ struct{} `cbor:",toarray"`
	// ebblock fields
}

func decode(data []byte) error {
	var b block
	err := cbor.Unmarshal(data, &b)
        if err != nil {
		return err
        }
	switch b.typ {
		case 0:
			var mb mainblock
			err = cbor.Unmarshal(b.rawBlock, &mb)
			...
		case 1:
			var eb ebblock
			err = cbor.Unmarshal(b.rawBlock, &eb)
			...
	}
}
```

## Another Approach - use stream-mode branch

Use [stream mode decoding](https://github.com/fxamacker/cbor/blob/feature/stream-mode/stream_decode.go) in branch https://github.com/fxamacker/cbor/tree/feature/stream-mode.  This branch was created for [Cadence](https://github.com/onflow/cadence/) in the [Flow](https://github.com/onflow/flow-go) blockchain.  It doesn't support stream encoding and decoding of float and map yet (not needed by Cadence).  **Warning**: this approach can be more error-prone and it requires user to be very familiar with CBOR data models.

**Comment by agaffney** [comment]
Thank you. That is very helpful.

I ended up coming up with a hacky workaround that utilizes `UnmarshalCBOR()` on my `struct`, strips off the first byte of the raw CBOR and then passes the rest through `Unmarshal()`, which will end up returning the first element of the array. This method is hacky and somewhat brittle, so I will probably switch to the `RawMessage` approach that you noted.
