### ISSUE TITLE
feature: Add decoder option (non-default) to allow decoding CBOR text string containing invalid UTF-8

### ISSUE THREAD

**Issue by fxamacker** [fxamacker/cbor#320]
This new option would allow users to override the default setting and decode CBOR text string containing invalid UTF-8.

The encoder allows encoding invalid UTF-8 to CBOR text string because CBOR RFC 8949 states:

> Generic CBOR encoders provide an application interface that allows the application to specify any well-formed value to be encoded as a CBOR data item, including simple values and tags unknown to the encoder.
>
>Even though CBOR attempts to minimize these cases, not all well-formed CBOR data is valid: for example, the encoded text string 0x62c0ae does not contain valid UTF-8 (because [RFC3629] requires always using the shortest form) and so is not a valid CBOR item. 

The decoder currently checks and prevents decoding CBOR text string containing invalid UTF-8.

Although I recommend specifying or using protocols that reject invalid UTF-8 strings in CBOR text strings, some scenarios might find it useful.

**Comment by x448** [comment]
@fxamacker Any chance this can be included in v2.5.0?

**Comment by zensh** [comment]
I am waiting for this feature.

**Comment by fxamacker** [comment]
@zensh This feature was ported to main branch in https://github.com/fxamacker/cbor/commit/ae9b14c9673566d1c790bf2d561cf51f206eaca4

However, the docs are not yet updated.  Thanks for letting me know, I will update docs.
