### ISSUE TITLE
feature: return buffer to the pool when using streaming codec

### ISSUE THREAD

**Issue by burdiyan** [fxamacker/cbor#332]
I'm not sure if this is a feature request or actually a bug.

If I'm not missing something, it looks like when using `cbor.NewEncoder()` the underlying `encoderBuffer` is never returned back to the pool.

[Here](https://github.com/fxamacker/cbor/blob/6cdde668b0489e70bc1b7fd81308d34465f48315/encode.go#L553) `getEncoderBuffer()` is called during `NewEncoder` but `putEncoderBuffer()` is never called afterwards.

**Comment by fxamacker** [comment]
Hi @burdiyan Thanks for reporting this!  :+1:   I looked into it and have some ideas to try.
