### ISSUE TITLE
feature: Support cbor patch

### ISSUE THREAD

**Issue by zensh** [fxamacker/cbor#337]
**Is your feature request related to a problem? Please describe.**
I would like to update a CBOR document like JSON Patch. It has a very wide range of uses.

**Describe the solution you'd like**
I was going to create a stand-alone cbor-patch library, but found that it relied on internal functions.
Can we implements cbor-patch feature here?

**Describe alternatives you've considered**

**Additional context**

**Comment by fxamacker** [comment]
@zensh CBOR Patch is interesting idea!  

I see that JSON Patch is defined in ([RFC 6902](https://datatracker.ietf.org/doc/html/rfc6902/)).  However, I didn't find a similar RFC for CBOR Patch.

I wonder if there's a better way than a direct translation of JSON Patch to CBOR Patch (to avoid being verbose).  Do you know if a CBOR Patch specification or RFC is in the works?
