### ISSUE TITLE
Add Fortanix, Tailscale, and National Cybersecurity Agency of France (govt) to notable users

### ISSUE THREAD

**Issue by fxamacker** [fxamacker/cbor#357]
Update list of notable users of fxamacker/cbor:

- [ ] @fxamacker - mention these in the README text.
- [ ] @x448 - please add these to the animated banner of notable users.  Also, maybe change ContainerSSH link to libcontainerssh instead of auditlog in the banner. :pray:

**Comment by x448** [comment]
Forgot about this...maybe doable this weekend for the animated banner (no promises).  I'll skip long names that don't fit.
