### ISSUE TITLE
feature: support diagnostic notation

### ISSUE THREAD

**Issue by zensh** [fxamacker/cbor#384]
**Is your feature request related to a problem? Please describe.**
https://www.rfc-editor.org/rfc/rfc8949.html#name-diagnostic-notation

I would like to make a PR.

**Comment by fxamacker** [comment]
@zensh yes, I think supporting Diagnostic Notation (DN) would be useful, but we should avoid affecting performance of regular CBOR decoding/unmarshalling  (`ns/op`, `B/op`, and `allocs/op`).

Please feel free to open PR and maybe include comparison output from `benchstat`.

BTW, in case you're interested, [Appendix G of RFC 8610](https://www.rfc-editor.org/rfc/rfc8610.html#appendix-G) defines the Extended Diagnostic Notation, which adds some extensions to DN.

**Comment by zensh** [comment]
@fxamacker Do you have any other suggestions? I can fix them.

**Comment by fxamacker** [comment]
@zensh The PR is looking good, I reviewed text string encoding today and need to continue reviewing the rest next weekend.

I was asked to take over a project at work and have been working more overtime than usual.  And my father passed away this year so my personal time was affected.

The  kindness of contributors on this project have been a welcome oasis.  Thanks again for your patience and contributions!

**Comment by fxamacker** [comment]
This is closed by PR #386.  Great work!  :tada:
