### ISSUE TITLE
Add comparisons for fxamacker/cbor, encoding/gob, encoding/json

### ISSUE THREAD

**Issue by x448** [fxamacker/cbor#391]
Benchmark comparisons to Go standard library codecs are missing.

Let's add benchmark comparisons of fxamacker/cbor, encoding/gob, and encoding/json.

Encoded size comparisons are important for some use cases.  Use simple table if there isn't enough time for charts.  Make it readable on phone (I wish I had this available on my phone yesterday).

Use a common data struct with realistic values for comparison.

UPDATE:  something like this...

| Codec | Benchmark | Duration </br>ns/op&nbsp;&nbsp; | Memory</br>B/op&nbsp;&nbsp;&nbsp; | Allocs&nbsp;&nbsp;&nbsp; </br>allocs/op | Encoded</br>Output&nbsp; |
| :---- | --------- | ------------: | -----: | -----: | ---: |
| fxamacker/cbor 2.5 | Marshal (K,P) | 201.4  | 176 | 2 | 80 bytes
| fxamacker/cbor 2.5 | Marshal (K) | 421.7  | 176 | 2 | 80 bytes
| fxamacker/cbor 2.5 | Encode (K) | 576.5 | 272 | 4 | 80 bytes
| ugorji/go 1.2.11 | Encode (K) | 1,408.0 | 1320 | 4 | 80 bytes
| encoding/json | Encode (K) | 850.9 | 368 | 4 | 129 bytes
| encoding/json | Encode | 670.5 | 336 | 4 | 179 bytes
| encoding/gob | Encode | 3,846.0 | 1,469 | 32 | 195 bytes
- Input: First example data in RFC 8392 Appendix A from a Go struct with `keyasint` tags.
- K = `keyasint` struct tag (or equivalent). &nbsp; P = b.RunParallel().
- go1.19.7, linux_amd64, i7-12700H laptop. `benchstat` on  `go test -bench=. -count=20`.

**Comment by x448** [comment]
This will show `toarray` and `keyasint` features shrinking encoded data size.

I can simulate the `keyasint` feature for encoding/json.  Didn't see any struct tags for encoding/gob.

**Comment by fxamacker** [comment]
@x448 This is a great idea.   However, I'm closing this (for now) so we can revisit and maybe reopen after v2.5.0 is released.

Comparisons in README can require time to update when any codec compared is updated.

Lack of time to update the README can be the only blocker to a new release being tagged, so we should reduce size of README first by removing or updating outdated comparisons that already exist.
