### ISSUE TITLE
Add "Core Deterministic Encoding" mode

### ISSUE THREAD

**Issue by fxamacker** [fxamacker/cbor#42]
When user specifies "Core Deterministic Encoding" mode, this library should:
1. encode floating point values using the shortest form that preserves that value
2. sort using streamlined rules that produce same results as "CTAP2 Canonical CBOR" sorting of map keys
3. no change needed for integers since they're already using shortest form for all modes

For example, try to convert float64 to float32, if that works, try to convert float32 to float16.

This mode makes serialized data more compact when it contains floating point numbers.

**Comment by x448** [comment]
This issue title should be changed to:  Add "Core Deterministic Encoding" mode.  

Encoding to shortest form of CBOR float that preserves value could be done when this mode is specified.

**Comment by x448** [comment]
Some people (not me) might prefer converting floating-point values all the way down to smallest integer type when the value can be preserved.  So this library should use a naming convention for new mode names.

These mode names are 100% clear about what "shortest form" of floating-point means:
* CoreDetEncFloat16 -- use float16 as shortest form for floating-point (~10x slower than 64->32)
* CoreDetEncFloat32 -- use float32 as shortest form for floating-point (fast from 64->32)

You may want to ask Carsten Bormann shortly before implementing this.

**Comment by fxamacker** [comment]
Issue #74 will provide a way to specify this mode.
