### ISSUE TITLE
feature: support `omitempty` for `toarray` at struct level

### ISSUE THREAD

**Issue by herrjemand** [fxamacker/cbor#425]
### What version of fxamacker/cbor are you using?

2.5.0

### Does this issue reproduce with the latest release?

Yes

### What OS and CPU architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
GO111MODULE=""
GOARCH="arm64"
GOBIN=""
GOCACHE="/Users/yuriy/Library/Caches/go-build"
GOENV="/Users/yuriy/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/yuriy/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/yuriy/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/opt/homebrew/Cellar/go/1.20.7/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/opt/homebrew/Cellar/go/1.20.7/libexec/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.20.7"
GCCGO="gccgo"
AR="ar"
CC="cc"
CXX="c++"
CGO_ENABLED="1"
GOWORK=""
CGO_CFLAGS="-O2 -g"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2 -g"
CGO_FFLAGS="-O2 -g"
CGO_LDFLAGS="-O2 -g"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/c_/hpk7wnh95_b4jm_tc3btcggm0000gp/T/go-build1363574290=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

When calling for complex struct encoding i get result cbor with all fields set to default values:

```
type Child struct {
	_     struct{} `cbor:",toarray"`
	Cnum  int
	Cstr  int
	Cintr interface{}
}

type Parent struct {
	A Child  `cbor:"257,keyasint,omitempty"`
	B []byte `cbor:"-258,keyasint,omitempty"`
}

results, _ := cbor.Marshal(Parent{})

log.Println(hex.EncodeToString(bts))
```

### What did you expect to see?

a0

### What did you see instead?

a1190101830000f6

**Comment by x448** [comment]
Nice find!  I can reproduce this using v2.5.0 and older version.

@fxamacker can this fit into next update?

**Comment by fxamacker** [comment]
@herrjemand thank you for reporting this! :+1:

I'll take a look this weekend and share what I find.

**Comment by x448** [comment]
BTW, this comment about `toarray` disabling `omitempty` in encode.go could be useful in Quick Start about struct tags.

```Go
// "omitempty" is disabled by "toarray" to ensure that the same number
// of elements are encoded every time.
```

**Comment by x448** [comment]
Here is different example where  `omitempty` for child struct is ignored by `encoding/json` and `fxamacker/cbor`.  

https://go.dev/play/p/rYIcjGu2rnZ

```Go
package main

import (
	"encoding/hex"
	"encoding/json"
	"fmt"

	"github.com/fxamacker/cbor/v2"
)

type Child struct {
	Cnum int
}

type Parent struct {
	A Child `json:",omitempty"`
	B int   `json:",omitempty"`
}

func cb() {
	results, _ := cbor.Marshal(Parent{})
	fmt.Println("hex(CBOR): " + hex.EncodeToString(results))

	text, _ := cbor.Diagnose(results) // Diagnostic Notation
	fmt.Println("DN: " + text)
}

func js() {
	results, _ := json.Marshal(Parent{})
	fmt.Println("hex(JSON): " + hex.EncodeToString(results))

	text := string(results) // JSON
	fmt.Println("JSON: " + text)
}

func main() {
	cb()
	fmt.Println("-------------------------------")
	js()
}
```

Output shows child struct A is not omitted and int B is omitted by `encoding/json` and `fxamacker/cbor`
```
hex(CBOR): a16141a164436e756d00
DN: {"A": {"Cnum": 0}}
-------------------------------
hex(JSON): 7b2241223a7b22436e756d223a307d7d
JSON: {"A":{"Cnum":0}}
```

**Comment by fxamacker** [comment]
@herrjemand Thanks again for reporting this!

@x448 Thanks for spotting the comment about `omitempty` being disabled by `toarray` and sharing a different example.

`omitempty` is disabled for `toarray`, so a struct with `toarray` tag will always encode as fixed-length array (with all fields).

To encode `toarray` struct as an empty array, I need to add support for `cbor:",toarray,omitempty"` at struct level:

```Go
// Original example
type Child struct {
	_     struct{} `cbor:",toarray"`

// Proposed new feature
type Child struct {
	_     struct{} `cbor:",toarray,omitempty"`

```

I will change this from bug to feature.  I think this new feature would be worthwhile.  Thanks for reporting!  :+1:

**Comment by herrjemand** [comment]
@fxamacker i think maybe if i make fields nullable then the parser will render them omited?

**Comment by fxamacker** [comment]
@herrjemand 

> i think maybe if i make fields nullable then the parser will render them omited?

Not when using `toarray` because `toarray` struct is encoded as fixed-length array and `omitempty` for fields are ignored.  We don't omit fields of a struct when encoding to CBOR array so we can decode CBOR array back to Go struct by index. 

Currently, codec encodes empty `Parent{}` as 1-byte CBOR data item `a0` if you avoid using `toarray` like this:  
https://go.dev/play/p/rTishcg5Kqs  
```Go
type Child struct {
	Cnum  int         `cbor:",omitempty"`
	Cstr  int         `cbor:",omitempty"`
	Cintr interface{} `cbor:",omitempty"`
}

type Parent struct {
	A Child  `cbor:"257,keyasint,omitempty"`
	B []byte `cbor:"-258,keyasint,omitempty"`
}
```

The simpler example by @x448 also encodes to 1-byte CBOR data item `a0` when modified like this:  
https://go.dev/play/p/JFrVTwWw3bT  
```Go
type Child struct {
	Cnum int `json:",omitempty"`
}

type Parent struct {
	A Child `json:",omitempty"`
	B int   `json:",omitempty"`
}
```

So the proposed new feature isn't needed except for the use case of combining `toarray` with `omitempty` at struct level.
