### ISSUE TITLE
Separate CTAP2 "canonical CBOR" and RFC 7049 "Canonical CBOR" encoding modes

### ISSUE THREAD

**Issue by x448** [fxamacker/cbor#43]
**CTAP2 "canonical CBOR" != RFC 7049 "Canonical CBOR"** when map keys have different data types due to sorting rules.  If all map keys have same data type, there's no difference.

When "Canonical CBOR" option is specified, this library has been using sorting rules from "Core Deterministic Encoding Requirements" making it effectively sort like CTAP2.

There should be two canonical modes as options: "Canonical CBOR" and "CTAP2 Canonical CBOR".  They only differ in sorting rules involving map keys with mixed types.

NOTE:  issue edited based on your comments

**Comment by fxamacker** [comment]
It seems CTAP2 is the way it works now for "Canonical CBOR" mode.  I can add CTAP2 as an encoding option along with Canonical mode, and then modify Canonical mode to use "length-first map key ordering".

Let's split this into 2 issues: 
- bug fix by adding CTAP2 mode and fix sorting for "Canonical CBOR",
- enhancement by supporting "Core Deterministic Encoding Requirements", which requires issue #42.

This would let me have v1.3.1 release with just this bug fix and issue #41.

**Comment by x448** [comment]
FWIW at least one popular library has this same bug in their latest release and also latest commit.
