### ISSUE TITLE
feature: Decode option to require case-sensitive field name matches

### ISSUE THREAD

**Issue by benluddy** [fxamacker/cbor#432]
**Is your feature request related to a problem? Please describe.**
I'm working on a project that serves and persists API resources in a JSON encoding. The existing JSON encoding is case-sensitive in matching JSON object keys to struct field names during decode. I would like to support CBOR as an alternative encoding with case-sensitive field matching.

**Describe the solution you'd like**
A new DecOption field that can disable fallback to case-insensitive field matching. The default would preserve the current behavior.

**Additional context**
It's particularly interesting when an input map has multiple case variations on a field tag. For example, if you're unmarshaling into:
```
struct {
  Foo string `json:"bar"`
}
```
The first matching key in the map wins. So "\xa2\x63bar\x65lower\x63BAR\x65UPPER" gives you "lower" and "\xa2\x63BAR\x65UPPER\x63bar\x65lower" gives you "UPPER". You can catch this if unknown field errors are enabled, but the map key that appears in the error also depends on where it appears in the input.

I'm happy to open a PR myself if you think this is a feature you'd accept.

**Comment by fxamacker** [comment]
Hi @benluddy, thanks for opening this issue!  This sounds very useful, please feel free to open a PR. :+1:

**Comment by fxamacker** [comment]
Hey @benluddy, I can review your PR this weekend (probably Sunday) if it is available.

If you haven't started yet, I can try to implement this feature over the weekend and add it to next milestone for release.

Currently, this library matches Go's `encoding/json` package for case-insensitive field names, but I really like your suggestion!  Thanks for opening this issue with details needed to make it easy to accept your suggestion! :+1:

**Comment by benluddy** [comment]
Thanks @fxamacker! I've just opened https://github.com/fxamacker/cbor/pull/433 for this.

**Comment by fxamacker** [comment]
Thanks again for opening this issue and PR!  I updated my last comment (above) to be more precise.

This is closed by #433! :tada:
