### ISSUE TITLE
Add support for CBOR Tags (major type 6)

### ISSUE THREAD

**Issue by fxamacker** [fxamacker/cbor#44]
UPDATED on Jan 30, 2020:

I've been working on adding support for CBOR tags and made good progress.  I moved this feature from v2.0 to [milestone v2.1](https://github.com/fxamacker/cbor/milestone/11).   

v2.0 will be released on Feb 2, 2020 and v2.1 about 1 week after that.

**Comment by x448** [comment]
Chunks with tags inside CBOR strings (major type 2 and 3) should be treated as malformed until you receive clarification for [RFC 7049bis tag-related clarification request](https://github.com/cbor-wg/CBORbis/issues/148).

I'd love to see 7049bis get updated to treat tagged chunks as malformed.  It should be a simple change to Appendix A and G like you mentioned in your request for clarification.

**Comment by fxamacker** [comment]
I posted [a message about this](https://mailarchive.ietf.org/arch/msg/cbor/D-mmEm5bnWlYYTxf44J1WBcTqLs) on the [CBOR mailing list](https://mailarchive.ietf.org/arch/browse/cbor/) and updated the [CBORbis (7049bis) issue](https://github.com/cbor-wg/CBORbis/issues/148) to match my newer (mailing list) text.

I'll work on other aspects of tag support and check periodically for feedback or clarification.

**Comment by fxamacker** [comment]
Jeffrey Yasskin provided helpful [feedback](https://mailarchive.ietf.org/arch/msg/cbor/NFp3pIZ7hKddGKF4kdfwT0ne34o) on the mailing list.  It seems I misread a line in the pseudocode.  

Tagged chunks are malformed and rejected by the pseudocode as it should be.
