### ISSUE TITLE
feature: CBOR uses a different definition of "empty" than golang encoding/json for omitempty

### ISSUE THREAD

**Issue by dinhxuanvu** [fxamacker/cbor#445]
**Is your feature request related to a problem? Please describe.**
My team is working on using CBOR along side of JSON for encoding internal golang type and notice that if we convert a go struct with `omitempty` tag in some case, the results don't match the JSON due to the fact CBOR uses a different definition of `empty` compared to `encoding/json` library in go.

For example, consider this go struct:
```
type Foo struct {
 Bar struct{} `json:"bar,omitemptry"`
}
```

If we marshal this struct into JSON, the Bar field will be reserved but in CBOR, it will be omitted completely. The reason is in go library, the "omitempty" option specifies that the field should be omitted from the encoding if the field has an empty value, **defined as false, 0, a nil pointer, a nil interface value, and any empty array, slice, map, or string** while in CBOR, an empty struct is also considered empty value. It would be helpful to have both of them using the same definition to ensure no data loss during the decoding process.

**Describe the solution you'd like**
We would like to add a [decode option](https://github.com/fxamacker/cbor/blob/master/decode.go#L377) to enforce the parity between golang `encoding/json` library and CBOR. This option will not introduce any breaking changes given this option needs to be enabled by users.

**Describe alternatives you've considered**
We can change the behaviors in `isEmptyStruct` directly to  match the ones in golang but this is a breaking change.

**Additional context**
We are happy to open the PR for this work.

**Comment by fxamacker** [comment]
@dinhxuanvu Thanks for opening this issue!  It makes sense, please feel free to open a PR.

BTW, `fxamacker/cbor` currently handles `omitempty` more similar to Go's proposed `encoding/json/v2`. 

Go's `encoding/json` and proposed `encoding/json/v2` handle `omitempty` [this way](https://github.com/golang/go/discussions/63397): 
- Current: `encoding/json` omits if field value is an empty Go value.
- Future: `encoding/json/v2` omits if field value would encode as empty JSON value.  


Also, here is a more complex `omitempty` example you might find useful.  If all fields of a nested struct are omitted, and the nested struct is tagged with `omitempty`, then the nested struct itself is omitted.

https://go.dev/play/p/0XUKz6bR6zN

```Go
	type T1 struct {
		Bo    bool           `cbor:"bo,omitempty"`
		UIo   uint           `cbor:"uio,omitempty"`
		Io    int            `cbor:"io,omitempty"`
		Fo    float64        `cbor:"fo,omitempty"`
		So    string         `cbor:"so,omitempty"`
		Slco  []string       `cbor:"slco,omitempty"`
		Mo    map[int]string `cbor:"mo,omitempty"`
		Po    *int           `cbor:"po,omitempty"`
		Intfo interface{}    `cbor:"intfo,omitempty"`
	}
	type T struct {
		Str  T1 `cbor:"str"`
		Stro T1 `cbor:"stro,omitempty"`
	}

	v := T{}

	b, _ := cbor.Marshal(v)
	fmt.Printf("CBOR in hex: 0x%xn\n", b) // CBOR in hex: 0xa163737472a0n

	edn, _ := cbor.Diagnose(b)
	fmt.Printf("CBOR in EDN: %s\n", edn) // CBOR in EDN: {"str": {}}
```

**Comment by dinhxuanvu** [comment]
The feature has been completed.
/close
