### ISSUE TITLE
docs: Unmarshal godoc doesn't mention that cbor.Tag is produced for unrecognized tags when decoding into empty interface

### ISSUE THREAD

**Issue by benluddy** [fxamacker/cbor#447]
### What is the URL of the content?

https://github.com/fxamacker/cbor/blob/6bbaf8b8e6ec38eadd54bdf5e19ed192583528a4/decode.go#L40-L53

### Please describe the problem.

When decoding a tagged data item into an empty interface value, Unmarshal produces a `cbor.Tag` if it doesn't recognize the tag number. (https://go.dev/play/p/EkGAJ5LnKdI)

**Comment by fxamacker** [comment]
@benluddy Thanks for spotting this and opening PR #448!

Closed by #448
