### ISSUE TITLE
Reject indefinite length byte string if chunks are indefinite length

### ISSUE THREAD

**Issue by fxamacker** [fxamacker/cbor#45]
Enforce this in data validation.

RFC 7049 2.2.2
```
   For indefinite-length byte strings, every data item (chunk) between
   the indefinite-length indicator and the "break" MUST be a definite-
   length byte string item; if the parser sees any item type other than
   a byte string before it sees the "break", it is an error.
```

This also affects indefinite length text string.

**Comment by x448** [comment]
The "byte/string" is confusing to me so it may also confuse others.

I think title should be "Reject indefinite length byte string if chunks are indefinite length" to use same terminology as RFC 7049.

The body of the issue can mention this also affects "indefinite length text string".
