### ISSUE TITLE
feature: Add option to ignore unrecognized tags when unmarshaling into interface{}

### ISSUE THREAD

**Issue by ssuriyan7** [fxamacker/cbor#470]
**Is your feature request related to a problem? Please describe.**
When unmarshaling a CBOR item into a Go interface{} value, and the item has an unrecognized tag number, the concrete object stored in the interface{} value is a cbor.Tag{} struct. In our project, there is a need to unmarshal CBOR into map[string]interface{} so that it can be used in places currently using encoding/json. The existing code that unmarshals JSON into map[string]interface{} and processes it, expects to deal with concrete values of certain types (bool, float64, string, []interface{}, map[string]interface{}, or nil). To achieve compatibility with the current code that uses encoding/json, there's a need to configure cbor's decode operation so that when it decodes an unrecognized tag into interface{}, it ignores the tag.

**Describe the solution you'd like**
Add a new decode option to make the behavior of ignoring unrecognized tags when unmarshaling into interface{} configurable. The option would allow compatibility with existing code that assumes decoding into interface{} produces something compatible with the encoding/json behavior.

**Additional context**
I'd be happy to contribute the changes needed for this issue.

**Comment by fxamacker** [comment]
@ssuriyan7 Thanks for opening this issue!  Please feel free to open a PR to add new decoding option for this!

**Comment by fxamacker** [comment]
Closed by #475.
