### ISSUE TITLE
[v2.6.0] Bump from `go 1.12` to `go 1.17` in go.mod

### ISSUE THREAD

**Issue by fxamacker** [fxamacker/cbor#478]
Go 1.12 is obsolete and Go 1.20 is a bit too new.  It seems reasonable to specify `go 1.17` in go.mod because that is the minimum version that can compile main branch without changes.

A recent PR bumped go.mod to `go 1.20` while still allowing Go 1.17 to work.  The go.mod can create the impression we don't support Go 1.17-1.19 if a user takes a quick look without reading comments, etc.

It seems reasonable to specify `go 1.17` in go.mod:
- it can avoid confusion about what minimum version we actually support
- it passed tests with when compiled with Go 1.17 to 1.21
- it will still use Go 1.18-1.20 features when compiled with Go 1.20+
- it is the first version to support the `//go:build` syntax and avoiding the old syntax is nice

Please comment here if you have thoughts or concerns about bumping from Go 1.12 to 1.17.

**Comment by x448** [comment]
@fxamacker most users won't read this issue until after v2.6.0 is released and only if it affects them.  You can release v2.6.1 as a fix to support earlier Go version if users open issue to request Go 1.16 or older.

**Comment by fxamacker** [comment]
Closed by #489
