### ISSUE TITLE
Add CBOR encoding/decoding speed comparison chart to README.md

### ISSUE THREAD

**Issue by x448** [fxamacker/cbor#48]
I'll provide a comparison using release versions of CBOR libraries. The input data won't be contrived/biased so it'll be fair and useful.  

README says speed isn't a primary design goal and that faster libraries exist, so I think the results will surprise some people.

**Comment by x448** [comment]
![image](https://user-images.githubusercontent.com/57072051/69882977-c6a0a580-1297-11ea-8b4e-1b1af918343a.png)

**Comment by x448** [comment]
![image](https://user-images.githubusercontent.com/57072051/69885102-264f7e80-12a1-11ea-8605-6164aafb8a87.png)

**Comment by fxamacker** [comment]
Thanks for doing these CBOR speed and program size comparisons!  Your pull request was merged.

**Comment by x448** [comment]
![image](https://user-images.githubusercontent.com/57072051/69992105-9c0c5200-150e-11ea-9888-9c50a0f41de2.png)

**Comment by x448** [comment]
![image](https://user-images.githubusercontent.com/57072051/69993581-b98eeb00-1511-11ea-98da-46d14ad0fdd0.png)
