### ISSUE TITLE
feature: add build tag for tinygo to move tinygo into main branch

### ISSUE THREAD

**Issue by x448** [fxamacker/cbor#499]
**Is your feature request related to a problem? Please describe.**

The branch for tinygo doesn't have changes from v2.6.0 yet.

**Describe the solution you'd like**

Use build tag to move tinygo support into main branch.

**Describe alternatives you've considered**

Update the tinygo branch to v2.6.0.

Maybe ask tinygo to implement some of the missing features or contribute some required features to tinygo.

**Comment by fxamacker** [comment]
@x448 thanks for requesting this feature!

Maybe we can combine your suggestion of bringing TinyGo into main branch with your alternate suggestion of reaching out to TinyGo to open issues and/or contribute missing features in TinyGo.

To save time, can you share list of missing features in TinyGo  v0.31 (no rush but maybe by next Saturday if possible)?  :pray:

**Comment by fxamacker** [comment]
Closed by new feature branch [feature/cbor-tinygo-beta](https://github.com/fxamacker/cbor/tree/feature/cbor-tinygo-beta):
- https://github.com/fxamacker/cbor/pull/582

It obsoletes old branch for tinygo.
