### ISSUE TITLE
Support `encoding.[BinaryMarshaler,BinaryUnmarshaler]`?

### ISSUE THREAD

**Issue by Yawning** [fxamacker/cbor#5]
Is there any interest in supporting special handling for types that know how to serialize themselves into a binary representation?  `encoding/json` supports calling a given object's `encoding.TextMarshaler` and `encoding.TextUnmarshaler` implementations if provided, as does the go-codec library.

For CBOR the binary equivalents probably make more sense.  I've started poking at this in a local branch, and while the encoding side was straightforward to add, the decoding side is a bit more involved due to `parseInterface`.

**Comment by fxamacker** [comment]
Thanks for the suggestion.  I'm looking into it.

You're right that encoding is easier than decoding for this.

**Comment by Yawning** [comment]
The commit from 3 days ago appears to work.  I'm still in the progress of migrating the codebase I wanted this for, but all of the issues encountered so far are "the code is dependent on how the old library did certain things".

Thanks!

**Comment by fxamacker** [comment]
Just published release v1.1.0 with this feature.  It passed 10+ hours of fuzzing.
