### ISSUE TITLE
question: how to correctly decode CBOR-encoded data that was encoded with `cbor.StringToByteString`

### ISSUE THREAD

**Issue by shanebishop** [fxamacker/cbor#500]
I see support for decoding and encoding CBOR data with byte strings was added in issue #446 in PR #465. I would like to use this feature in order to automatically transform input data that can include invalid UTF-8 into CBOR that I can successfully decode (if this is a misuse of the feature, please let me know).

I encoded some data in CBOR with the following encoding options:
```go
options := cbor.CoreDetEncOptions()
options.Time = cbor.TimeRFC3339Nano
options.String = cbor.StringToByteString
```

I am now trying to decode the CBOR, but everything I have tried so far gives me an error.

This code gives me the error `cbor: cannot unmarshal byte string into Go struct field wmd.WmdEvent.created of type time.Time`:
```go
decMode, err := cbor.DecOptions{ByteStringToString: cbor.ByteStringToStringAllowed}.DecMode()
if err != nil {
	return nil, err
}
err = decMode.Unmarshal(b.Bytes(), v)
```
When I use
```go
cbor.DecOptions{DefaultByteStringType: reflect.TypeOf(cbor.ByteString(""))}.DecMode()
```
I get the error `cbor: cannot unmarshal byte string into Go struct field wmd.WmdEvent.id of type string`.

How can I correctly decode my CBOR data?

**Comment by benluddy** [comment]
Hi @shanebishop, have you tried:

```go
cbor.DecOptions{
  ByteStringToString: cbor.ByteStringToStringAllowed,
  DefaultByteStringType: reflect.TypeOf(""),
}
```

ByteStringToStringAllowed should let you decode a CBOR byte string into the string field.

When decoding into time.Time, the current implementation effectively decodes the data item into interface{}, then tries to convert the resulting Go value to time.Time: https://github.com/fxamacker/cbor/blob/cfbd0ff46d6af971bc530964f1fa4960bad305b6/decode.go#L1270-L1300

In any case, the above configuration for DefaultByteStringType should allow you to decode an untagged byte string into time.Time. I'm not sure it's desirable that an option controlling decodes into interface{} has a side effect on decodes into time.Time. I was surprised to discover it for myself yesterday (https://github.com/fxamacker/cbor/issues/497#issuecomment-1967549528).

**Comment by shanebishop** [comment]
Thanks @benluddy, your suggestion worked! 🎉

Now I just need to figure out how to get `com.fasterxml.jackson.dataformat.cbor.databind.CBORMapper` in the consuming Java application to play nice with the byte string-encoded CBOR, but that is outside the scope of this question.

**Comment by fxamacker** [comment]
Hey @shanebishop, thanks for opening this issue!

Based on [more discussion](https://github.com/fxamacker/cbor/issues/497#issuecomment-1975330919) with @benluddy, the workaround currently relies on unintended side effect :lady_beetle: of implementation details.

New feature/bugfix for this will be implemented this month (probably by adding a new decoding option).

I'll open new issue and will also comment here when the new feature becomes available for you to try.
