### ISSUE TITLE
Include bar chart of binary sizes in README

### ISSUE THREAD

**Issue by fxamacker** [fxamacker/cbor#6]
![image](https://user-images.githubusercontent.com/33205765/67166075-ddc3ad80-f351-11e9-8920-f77aa70fddc0.png)

**Comment by fxamacker** [comment]
Done.

**Comment by fxamacker** [comment]
![image](https://user-images.githubusercontent.com/33205765/67167109-9cd09680-f35b-11e9-9ded-be6bc9a77c1a.png)

**Comment by fxamacker** [comment]
![image](https://user-images.githubusercontent.com/33205765/67440168-11a30b00-f5be-11e9-8d23-f2ad799d30d4.png)

**Comment by x448** [comment]
![image](https://user-images.githubusercontent.com/57072051/69281068-3e424680-0bad-11ea-97ab-730b3d3069af.png)
