### ISSUE TITLE
CTAP2 shouldn't encode floating-point NaN values as 0xf97e00

### ISSUE THREAD

**Issue by x448** [fxamacker/cbor#88]
RFC 7049 Canonical CBOR requires encoding NaN values to 0xf97e00.

But CTAP2 Canonical CBOR forbids changing floating-point representations.  I believe this means do not encode all float64 NaN or all float32 NaN to 0xf97e00.

In practice, this difference would only be noticed if CTAP2 Canonical CBOR is required and floating-point data has NaN values.

This item was extracted from issue #86.

**Comment by fxamacker** [comment]
This is resolved by adding NaNConvertMode option to EncOptions and having CTAP2EncOptions() return EncOptions with NaNConvert=NaNConvertNone.  

Users can also modify the returned EncOptions.
